### ISSUE TITLE
Question about jekyll-assets and site.static_files array

### ISSUE THREAD

**Issue by aripalo** [envygeeks/jekyll-assets#101]
# Background

I use jekyll-assets and I have written a plugin of my own which optimized images. This plugin depends on `site.static_files` array which Jekyll exposes for [generators](http://jekyllrb.com/docs/plugins/#generators).

My image optimization plugin used to work as all my images were located outside of jekyll-asset's sources (in `images` folder at project root).

As jekyll-assets makes handling image assets easier as well and I moved my images to `_assets/images`. Jekyll and jekyll-assets work fine and serve my posts with images correctly, **BUT** now the `site.static_files` array does not contain my images anymore, which means that my image optimization plugin doesn't optimize anything.
# The actual question(s)

**Is it by design that jekyll-assets plugin does not include assets handled by it into `site.static_files`...?**

If it's by design, could there be anyother way of tapping into the assets used or in my image optimization plugin should I just glob through the `_assets` folder and collect the files with that?

Or could this be a bug in jekyll-assets or just misconfiguration on my project?

**Comment by abeMedia** [comment]
Do preprocessors run before or after proxies? I use magick to resize & crop the images and was considering the solution in https://github.com/jekyll/jekyll-assets/issues/297#issuecomment-227524129 however not having to add a proxy to each img tag makes this solution quite attractive.

**Comment by caub** [comment]
Does the optimized images replace the old images? or they are created in another folder? because I don't see size change for the moment:

I have for example _assets/img/image2.jpg image2.jpg 130KB and _assets/img/image2-4826e2b0b15c91f0dcdff75ab2ec7f907cddc58db665ffa97e0ff05c13823840.jpg 130KB too

```rb
# file: _plugins/jekyll-assets.rb
require "jekyll-assets"
require "image_optim"

image_optim = ImageOptim.new(:pngcrush => false, :pngout => false, :advpng => false, :jhead => false, :jpegoptim => false, :jpegtran => false, :gifsicle => false)
processor = proc { |_, data| image_optim.optimize_image_data(data) || data }

%w(image/gif image/jpeg image/png image/svg+xml).each do |type|
  Sprockets.register_preprocessor type, :image_optim, &processor  
end
```
and this in build script
```yml
npm i -g svgo mozjpeg optipng-bin pngquant-bin
#...
bundle exec jekyll build
```

**Comment by envygeeks** [comment]
Optimized images aren't replaced in your source (in that we don't alter your actual source files,) we alter them and store them in `.asset-cache` or whatever your cache folder is and then we use that.  You should check your cache folder and you should see a folder for the actions we do outside of Sprockets.

**Comment by caub** [comment]
Thanks hmm, ok, I added that folder in .gitignore, so that might be the problem

**Comment by aaronwolen** [comment]
Following up on @abeMedia's first question concerning the order of preprocessors and proxies: [the image optimization solution posted on the wiki](https://github.com/jekyll/jekyll-assets/wiki/Extras:-Image-Optim) works perfectly except in cases where an image magick proxy is used to resize the image.

I believe what happens is the image is optimized and *then* resized, effectively producing an unoptimized image.  The solution proposed in #297 avoids this issue but requires adding a new proxy to every image. 

Is it possible to use the wiki solution but postpone optimization until the images have been resized?
