### ISSUE TITLE
Overriding CSS and JS tags and generating asset_path without renaming the file to MD5

### ISSUE THREAD

**Issue by nalmeida** [envygeeks/jekyll-assets#11]
Jekyll Assets is great but, I would like to be able to change some things such as:

```
STYLESHEET = '<link rel="stylesheet" type="text/css" href="%s">'
```

Is it possible to be done extending / overriding in the `_plugin` ? If yes, what is the best approach?

I also would like to use the `{% asset_path test.jpg %}` without renaming the file to MD5. Is there any config option to disable it?

**Comment by kylekirkby** [comment]
Is there going to be any documentation added so we know how to use these features without crawling through ruby ?

**Comment by envygeeks** [comment]
They're not documented because they're not supported anymore.

**Comment by kylekirkby** [comment]
Ok, no problem thanks for the info!
