### ISSUE TITLE
Support web components

### ISSUE THREAD

**Issue by razor-x** [envygeeks/jekyll-assets#155]
@ixti For the next release, have you though about adding web component support? This is really the future of the web. Maybe this deserves its own issue, or maybe it's beyond the scope of this project. Either way I believe it's a very much needed solution.

Since this uses sprockets as a backend, maybe others have solved a similar problem with https://github.com/ahuth/emcee or https://github.com/alchapone/polymer-rails. Looks like this might even be a sprockets level plugin that can be supported directly: https://github.com/nevir/hackish-sprockets-htmlimports. There are a lot of options here it seems. Probably related to #139.

I don't know any easy way to add components into the asset pipeline with Jekyll or other static generators without using something separately and manually like Grunt or Gulp, etc. Even then, there is no obvious way to handle concatenation or asset name hashing.

It seems that [Vulcanize](https://github.com/polymer/vulcanize) is the official way to handle this process, so maybe the answer lies in hooking into that, or maybe we need a jekyll-vulcanize gem. If so, probably best to use as much of Vulcanize as possible rather then reinvent it.

Components are installed as bower packages as a collection of html, css, and js (I don't think they are distributed with any preprocessor languages yet). The real issue is you will have something like

``` html
<link rel="import" href="components/google-map/google-map.html">
```

That html file will be in bower_components and may reference additional js and css files via relative paths. The issue is there is no way to use Jekyll assets to tell Jekyll to add the html file and the associated assets into the _site build.

See the [Polymer Project](https://www.polymer-project.org/1.0/) and an example web component: https://github.com/Polymer/paper-dialog/blob/master/paper-dialog.html

**Comment by envygeeks** [comment]
I'm wondering if this isn't already supported in Sprockets 3, when debugging the new jekyll-assets I noticed that there is something about bower and all that, I'll play with this over the weekend and see what I can find out.

**Comment by razor-x** [comment]
Cool. It's all pretty new at this point. Polymer 1.0 was just announced at I/O this yeas (https://github.com/polymerelements/polymer-starter-kit) and other frameworks are starting to support web-components in various ways.

I think that ideally this would be handled by Sprockets and all one would need (after adding the elements to bower.json or in the Sprockets path) is something like

```
{% import components/google-map/google-map.html %}
```

The only issue with this sort of approach is that `google-map.html` will import other `.html` components using `<link>` and the expected result after processing with Sprockets might be a `google-map.html` file with the imports all inlined. The issue here is that once you start importing more then one component you have a lot of duplication as polymer, etc. will be inlined in each file.

An alternative might avoid inlining things and just process and move each nested resource independently. Thus you would expect to end up with many html, css, and js files all refercning each other. This is how the system works "in the wild". The issue here is 1) if you want like have features like  cache-busting hashed names, you need to make sure all the processed files get updated references and 2) you loose all the performance optimizations that come from concatenation and minimizing http requests.

I think these two issues is what https://github.com/polymer/vulcanize is meant to address.

**Comment by envygeeks** [comment]
After further research @razor-x we don't need to do anything special, it looks like we have support for this out of the box, you just need to add this to your `.bowerrc`

```
{
  "directory": "_assets/javascripts"
}
```

And boom, Sprockets will do the rest, that is what is implied here: http://crypt.codemancers.com/posts/2014-12-10-bower-with-rails/

**Comment by razor-x** [comment]
@envygeeks I'm not sure we are talking about the same thing here. :smile: The components discussed in that post are just [Bower](http://bower.io/) managed dependencies (typcially installed to `bower_components` by default). Generally they could be any type of asset, not just JavaScript. I would actually recommend against using `.bowerrc` like that. Instead just add `bower_components` to the sources list,

```yaml
assets:
  sources:
    - bower_components
```

For example, I've been doing this with `jekyll-assets` version 1.0.0 and before for a while now. You can then include assets from bower components normally

See for example:
- [bower.json](https://github.com/razor-x/jekyll-and-zurb/blob/d58269745835534be982a2e3f53d5399c8b6893b/bower.json#L15-L25)
- [_config.yml](https://github.com/razor-x/jekyll-and-zurb/blob/d58269745835534be982a2e3f53d5399c8b6893b/_config.yml#L41)
- [app.css.sass.erb](https://github.com/razor-x/jekyll-and-zurb/blob/d58269745835534be982a2e3f53d5399c8b6893b/_assets/stylesheets/app.css.sass.erb)

The web components I'm referring to are an upcoming standard (see https://en.wikipedia.org/wiki/Web_Components and https://developer.mozilla.org/en-US/docs/Web/Web_Components). Supporting them in an asset pipeline presents some interesting challenges, some of which I noted earlier. For example, take a look at one example on how ember-cli can load them: https://gist.github.com/dnegstad/eee660aa32efd906082c. The broccoli-vulcanize package is doing the heavy lifting there via https://github.com/polymer/vulcanize. That example is a little outdated, but the key elements are there. I was able to get it working recently [with a few changes here](https://github.com/rxlabs/ember-experiments/tree/eac37b74830527b5e2ec476787030226784ff13b).

Anyway, ideally, Sprockets or a Sprockets plugin would handle most of the work, and jekyll-assets would provide corresponding liquid tags and such for components. Alternatively, I could imagine having a pre-compile step handled by some node-based asset pipeline which would produce compiled assets consumable by Sprockets. But then one has to maintain a separate build system outside of Jekyll.

**Comment by envygeeks** [comment]
What exactly do you want out of Jekyll Assets, your argument jumps all over the place and is a goose chase, I'm not chasing the goose.  I want to know exactly and with clarity what you are banging on about.

**Comment by razor-x** [comment]
Ok, first off, it was not my intent to aggravate you. Let me attempt to outline my last post to clarify what is going on here.

1. The reason you gave for closing this ticket is that **web components** are already supported. However, the post you linked to as an example of that actually shows **Bower components** are already supported. These are completely different things.

2. I illustrated this by giving an example on how I was already using **Bower components**. I then gave an example of what another assets pipeline does in order to support **web components**.

3. Since web components are so new, there is not an obvious way to handle them yet. Thus, this issue could serve as a discussion about how, and at what level, jekyll-assets should support them. (I then gave some ideas to that effect.)

4. If you do not want to support them, or want to close this ticket for a different reason, that is certainly your right. I just didn't want to see the issue closed with "this works," when it doesn't. That would be misleading to users and contributors.

Finally, regarding,
> What exactly do you want out of Jekyll Assets

If you feel previous posts lacked such clarity, again I am mostly brainstorming ideas on what I've seen other people doing to support this new web standard **in order to open a discussion on how jekyll-assets might choose to implement support for web components.**

**Comment by envygeeks** [comment]
@razor-x I'm not aggravated, I just don't get what you want, it seems somebody else thought when I said "banging on" it was a bad thing but that just means "going on" or "talking about".  I just want clarity :cry:

**Comment by envygeeks** [comment]
Trust me, I do want to support your feature, I just want to know exactly what you want out of the feature so I can support it.  I deal with hundreds of tickets a day across multiple platforms so I generally don't like to click links and do research, so it would be great if you could provide examples and encapsulate everything you linked to for me to look at here.

**Comment by envygeeks** [comment]
@razor-x so I looked at the very first link, and I see what you are talking about.  Let me see what I can work out today based on the Polymer documentation, I actually had a client ask about that not to long ago and it just dawned on me they are using the same technology.

I'll start a web-components-wip and see and what I can work out to handle that kind of stuff.

**Comment by razor-x** [comment]
Totally understandable. I will make another post summarizing the two examples I linked to with abbreviated code blocks that get the important ideas across without having to click the links. I figured this would be a longer-term feature as it may depend on Sprockets or Sprockets plugins to support it first.

As to a detailed explanation of what web components are: that's a bit beyond the scope of this thread. For anyone looking to learn more, there have been some excellent Google I/O talks every year on this and Polymer.

**Comment by envygeeks** [comment]
@razor-x if you have links to videos or audio I can listen to while working on other stuff, that kind of stuff I will for sure listen to and watch on my free time so feel free to link to any you have on hand so I can learn more about it.

**Comment by razor-x** [comment]
@envygeeks I'll link a playlist in the next post. Here is the bower components stuff. I just noticed some of this was added to the README, but I'll post it anyway as I've already written it up. 

## Using Bower components with jekyll-assets

`package.json`
```json
{
  "scripts": {
    "install": "bower install"
  },
  "private": true,
  "dependencies": {
    "bower": "^1.6.5"
  }
}
```

`bower.json`
```json
{
  "name": "jekyll-site",
  "private": true,
  "dependencies": {
    "fastclick": "1.0.6",
    "normalize-css": "3.0.3"
  }
}
```

`_config.yml`
```yaml
assets:
  sources:
    - bower_components
```

Run `$ npm install`. Then include normally, e.g.,

`main.sass`
```css
//= require normalize-css/normalize.css
```

or use `@import` or in a template: `{% stylesheet normalize-css/normalize.css  %}`. Same sort of thing for javascript or image assets. The Bower components just become assets you can pull like any others.

Note that sometimes you only need to use the name of the component and Sprockets seems to use the main file specified by that components `bower.json`. The extension is also sometimes optional (if no name conflict), but this all varies by component.

**Comment by razor-x** [comment]
## Web component videos from I/O

- Good intro: [Google I/O 2014 - Polymer and Web Components change everything you know about Web development](https://youtu.be/8OJ7ih8EE7s)
- How they built apps with Polymer: [Google I/O 2015 - Polymer and modern web APIs: In production at Google scale](https://youtu.be/fD2As5RmM8Q)

## How an Ember.js project can use web components

1. Add webcomponentsjs and any web components, e.g., polymer elements, as Bower dependences.

2. Put all html imports in `app/elements.html`, e.g.,

   ```html
   <link rel="import" href="../bower_components/core-elements/core-elements.html">
   <link rel="import" href="../bower_components/paper-elements/paper-elements.html">
   ```

3. Include webcomponentsjs and the vulcanized import in `app/index.html`

   ```html
    <script src="vendor/webcomponentsjs/webcomponents.js"></script>
    <link rel="import" href="assets/vulcanized.html">
   ```

4. Add webcomponentsjs to the pipeline and create the vulcanized file from `elements.html`
   (note you need to install the appropriate broccoli plugins for this)

   ```js
   webcomponents = new Funnel('bower_components/webcomponentsjs', {
     destDir: '/vendor/webcomponentsjs',
     include: ['webcomponents.js']
   });

   vulcanized = Vulcanize('app', {
     input: 'elements.html',
     output: 'assets/vulcanized.html',
     stripExcludes: false,
     stripComments: false,
     inlineScripts: false,
     inlineCss: true,
     implicitStrip: false,
     excludes: [/^data:/, /^http[s]?:/]
   });

   return app.toTree([
     webcomponents,
     vulcanized
   ]);
   ```

So you end up with `webcomponentsjs.js` loaded like any other js lib and a single html import, `vulcanized.html`, which is generated by Vulcanize (using the specified compile options) from all of the individual imports listed in `elements.html`.

**Comment by envygeeks** [comment]
Well, I know we probably won't handle it like ember though it seems like we don't need to, but we will probably be adding an `{% component %}` that will let you create a link with the import stuff with us handling the rest of the stuff.

I don't know exactly how it will work but we can never work like ember, that's just too tightly coupled, we will more than likely end up just giving you access to them, writing them for you and creating a helper for you to include them.

Does that seem okay?

**Comment by razor-x** [comment]
I think the key is that web components really want to be Vulcanized, but it's definitely beyond the scope of jekyll-assets to do that. In the ember example, `app/elements.html` and `vulcanized.html` are both valid html imports, the main difference being one has been optimized and the other has not.

I believe that if `{% component %}` handled html imports similar to how the other tags handled js and css, that should be enough (at least for now). Since one is already using bower (a Node package), one can easily use Vulcanize to generate a `vulcanized.html` which could then be used like `{% component vulcanized %}`.

However, the big difference between an html import and a normal js or css asset is that **an html import can reference other assets (js, css, img, fonts, etc.)** using normal html tags. It can even (and will in more cases) import other html imports! It's :turtle: all the way down. This is where the challenge comes in.

Say you do `{% component my-button %}` which generates the asset `assets/my-button/my-button-cachebust.html`  but the `my-button` element expects `my-button.png` either via `<img>` or a css rule. Lets assume in `my-button.html` there is a line like

```html
<img src="my-button.png">
```

Then how do we ensure that we create `assets/my-button/my-button-cachebust.png` and the line in `my-button-cachebust.html` gets updated to point to the right path?

Now, I know Vulcanize can be set to inline and dudupe a lot of this, maybe even to the extent that nothing is referenced externally, but for a general html import, this nested asset referencing will exist. You could just decide to copy each entire component directory over to `_site/assets` and not touch the references, but then the subassets loose out on all the nice things like cachebust and minification.

**The main point is that however you decide to implement it, the 'nesting problem' has to be addressed somewhere.**

**Comment by envygeeks** [comment]
That's going to be the hardest part, but you already pointed to a library that works with polymer and supports Sprockets (whether it supports Sprockets 3 I don't know) and I can chop that up and see how they do it, and it seems that Google's own programmers even chipped in some code so that might be a good place for me to see how they manage to handle all that (if they even do.)

**Comment by envygeeks** [comment]
One thing I might end up doing is just offloading it onto nodejs, I'm not afraid to make it a requirement of a feature if the feature demands it (we have a few of those already) and even if I do it doesn't matter because you'll already have it and expect it anyways so we can always work around this complex issue by handling it both inside and outside of Ruby and Sprockets to chop together easy support.  Ultimately I'll play around with multiple implementation on trials and see what works the cleanest for both our sustainability and your usability.

**Comment by razor-x** [comment]
I'm just finishing up a new minimal [Jekyll skeleton](https://github.com/makenew/jekyll-site) using this plugin, and I wanted to include the new version of modernizr which must be generated from a config file. The way I ended up including it gave me an idea for how to deal with web components.

Here is a [minimal demo](https://github.com/makenew/jekyll-site/tree/polymer) with a single button and no special arguments to `vulcanize`. Honestly, it's probably fastest to just [look at the diff](https://github.com/makenew/jekyll-site/commit/4ef90a8f60825c033292fc6ea0091a24eb3b74f3) to see exactly what needs to be added for a typical project, but I'll summarize the required steps here. Adjust the paths where appropriate to match your project structure.

1. Add `polymer` and other web components as Bower requirements.
2. Add vulcanize to the npm devDependencies and do something like this in `package.json`:

   ```
   "scripts": {
     "install": "npm run bower",
     "postinstall": "npm run vulcanize",
     "bower": "bower install",
     "vulcanize": "vulcanize src/_assets/elements/elements.html > src/_assets/elements/vulcanized.html"
   }
   ```

3. Create `src/_assets/elements/elements.html` with imports like

   ```
   <link rel="import" href="../bower_components/paper-button/paper-button.html"> 
   ```

4. Make sure `src/_assets/elements` is added to the Jekyll Assets sources. Add `vulcanized.html` to `.gitignore`.

5. Include this in your `<head>`:

   ```
   {% javascript webcomponentsjs/webcomponents-lite %}
   <link rel="import" href="{% asset_path vulcanized %}">
   ```
