### ISSUE TITLE
Serving up 2x assets

### ISSUE THREAD

**Issue by zwaldowski** [envygeeks/jekyll-assets#39]
I'm almost certain that this is more a question for the Sprocket folks, but I'm also inexperienced enough with Ruby to feel the need to ask at the highest point in my stack.

We're currently using [retinajs](http://retinajs.com) for serving up double-sized assets to high-resolution screens, however migrating to jekyll-assets and using `asset_path` has left us with no copied `@2x` images in the resulting compiled site, since of course jekyll-assets thinks they're not being used anywhere.

Is there any immediate quick-and-easy way to extend jekyll-assets+Sprocket to look for and copy these unreferenced files? I see that jekyll-assets is eminently patchable, I just don't know Ruby enough to know what to do with that information.

**Comment by tonyarnold** [comment]
Does this still work as expected? Proper retina support in this plugin would be really nice to have — please reconsider adding it.

**Comment by ixti** [comment]
It still works as I last time described :D

But I think of enhancing `image` tag helper to support `@2x` option, which will look something like this:

``` html
<!-- with defualt @2x suffix -->
{% image header_bg.jpg [@2x] %}

<!-- with custom suffix -->
{% image header_bg.jpg [@2x:-retina] %}
```

**Comment by tonyarnold** [comment]
For the time being, I did this: https://gist.github.com/tonyarnold/e610c22dcfbb98cfc8fe
