### ISSUE TITLE
nokogiri error with jekyll-assets v3.0.0

### ISSUE THREAD

**Issue by bzle** [envygeeks/jekyll-assets#445]
- [x] I tried updating to the latest version.

Not sure what the OS is. I'm using Cloud Cannon to build the Jekyll sites.

## Description

Today I noticed one of my websites wouldn't build and I hadn't made any changes that could have broken things. The error was in regards to installing a dependency, nokogiri:

"An error occurred while installing nokogiri (1.8.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.1'` succeeds before bundling."

Then I noticed that my other Jekyll sites wouldn't build either. I got in touch with Cloud Cannon support and Mike eventually found that jekyll-assets had recently made a new release (v3.0.0), just earlier today. Specifying v2.4.0 for jekyll-assets in my Gemfile cleared up the issue.

## Output
```
```
## Expected

**Comment by envygeeks** [comment]
We require Nokogiri to do advacned HTML processing and building.  This is a problem with CloudCannon's platform and them not providing you with the necessary dependencies.  If you update the error I might change my opinion but I see no error so I'm inclined to assume that's the case in blind judgement.

**Comment by bzle** [comment]
Thanks for the reply Jordan (and congrats on the big update!). Responsive image support looks particularly interesting.

I'll update here if I learn anything, but for now I don't have any additional information.

**Comment by envygeeks** [comment]
If you can provide an output of the build log, that would help a lot, you don't need to post it publically, you can email it directly to me if you need.  I've also emailed CloudCannon to find out more about their infrastructure so I can see where to go from there.

**Comment by bzle** [comment]
Awesome, thank you. I'll send you an email.

**Comment by envygeeks** [comment]
Mike from CloudCannon just got back to me, so I've asked him what version of Nokogiri they have preinstalled so that I can release a new version that marks that as the minimum version, which will get your builds working again hopefully.  Unless he emails back stating they plan on upgrading pretty quickly.

**Comment by bzle** [comment]
Great! Thanks Jordon!

**Comment by envygeeks** [comment]
Has this been solved? I heard they upgraded, and we've since released 3.0.1 to resolve other known issues with some stuff.  Wondering if I need to keep in contact with them to see if there are still problems.

**Comment by bzle** [comment]
Not quite sure. Mike said you released 3.0.1 and that fixed the required issue, but now there's an uglify error.

I just tested using 3.0.1 and ran into the same Nokogiri error. Not sure why.

Really, I can live with 2.4.0. It's working as expected, and that's really all I need at the moment! I'm guessing there are other people using Cloud Cannon and jekyll-assets... but who knows.

**Comment by envygeeks** [comment]
Makes sense to stick with 2.4 instead of reporting possible bugs.  :roll_eyes:
