### ISSUE TITLE
3.0.0 and higher: Crash on build

### ISSUE THREAD

**Issue by appwrx** [envygeeks/jekyll-assets#450]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [X] I Am on OS X

## Description
Hi, 
since I update to Version 3.0.0 and higher this shows up everytime :(
Greets 
Alex

## Output
/Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/utils.rb:93: warning: else without rescue is useless
/Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/patches/cached_env.rb:5:in `require_relative': /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/utils.rb:82: syntax error, unexpected '.' (SyntaxError)
        if args[:asset]&.key?(:type)
                         ^
/Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/utils.rb:348: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/patches/cached_env.rb:5:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:16:in `require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:16:in `block (2 levels) in require_all'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:15:in `each'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:15:in `block in require_all'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:15:in `each'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:15:in `require_all'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets/env.rb:11:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:20:in `require_relative'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-assets-3.0.0/lib/jekyll/assets.rb:20:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler/runtime.rb:95:in `require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler/runtime.rb:95:in `rescue in block in require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/bin/jekyll:23:in `load'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/bin/jekyll:23:in `<main>'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Alex/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'

**Comment by envygeeks** [comment]
This error is caused by safe navigation.
We only support Ruby 2.3+, as noted in the documentation.
Please upgrade your Ruby.
