### ISSUE TITLE
Make Liquid Drops writable or skip html output

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#452]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Description
As suggested in issue [#448](https://github.com/envygeeks/jekyll-assets/issues/448#issuecomment-347102685) it would be useful to have writable liquid drops. They could come in handy if you only want to include the asset and need some information about it, but you don't want the html to be generated in place.

## Possible implementation
I think it could be implemented in two different ways (just leaving random ideas here):

#### Option 1) Referencing an asset which hasn't been processed yet will implicitly trigger its inclusion both in the list and the output folder:
`<a href="{{ assets['img/my_image.jpg'].digest_path }}">Link text</a>`

#### Option 2) Use a specific keyword to add an asset without outputting any html (`nohtml` keyword used here for the sake of the example):
<code>{% asset img/image1.jpg **nohtml** %}</code>

## If that's not possible
At the moment I have an *hacky* workaround: create a *dummy.html* page which won't be shown nor accessible by the users:
```html
<!-- This html page won't be shown to the users -->
{% asset img/image1.jpg %}
{% asset img/image2.jpg %}
```
This allows me to use the following code, referencing the processed assets in the output folder:
```html
<a href="{{ assets['img/image1.jpg'].digest_path }}">Link to image 1</a>
<a href="{{ assets['img/image2.jpg'].digest_path }}">Link to image 2</a>
```

**Comment by envygeeks** [comment]
I see what you meant earlier now, and what you want to do is already possible, please see the documentation: https://github.com/envygeeks/jekyll-assets#arguments

If the purpose of wanting writable drops, I don't think that's a valid reason to change their behavior.

**Comment by gasparesganga** [comment]
You'll have to excuse me but I can't understand how can I achieve this looking at the documentation about the argument (I am feeling dumb right now ehehe). Could you make an example please?

Version 2.x used to process all the assets matched by the `assets` filter, which required some fancy regex writing to prevent a load of useless or unwanted files to be processed. Now, without the `assets` key in the options all the assets that are not expicitly uset are not processed and this is a great change, I love it! But this change combined with the lack of `{% asset_path %}` tag creates the need I exposed in this ticket.

I have no problem in keeping using the *dummy html page hack*, it's just to understand better.

**Comment by envygeeks** [comment]
The documentation clearly states to use `{% asset yourAsset @path %}`.

**Comment by envygeeks** [comment]
Sorry didn't mean to close.

**Comment by envygeeks** [comment]
> Version 2.x used to process all the assets matched by the assets filter in the options

This is now the `preload` key, and it accepts shell expandables like `*` (actually that's all we accept) so you can precompile actual assets, but if you have assets that need to be copied we now also have `raw_precompile` which skips the pipeline and just copies large sets of data (like emoji's from Twemoji npm module.)

> I love it! But this change combined with the lack of {% asset_path %} tag creates the need I exposed in this ticket.

`{% asset yourAssest.jpg @path %}` as the documentation states.

**Comment by gasparesganga** [comment]
Yep, `@path` is exactly what I was looking for.
Shame on me for not having tried it before. The maning and use of those arguments weren't clear at all (at least for me).

Also, thank you for the clarification about `precompile` and `raw_precompile`. I was wondering where the old `asset` option had gone and I didn't get the meaning of these two new options.
Maybe the documentation would need some integrations in order to be clearer and provide more examples. One could feel a little *overwhelmed* by the whole jekyll-assets at first and even somebody who has been using it for quite some time and took his time to experiment and understand deeply how v2 worked, could feel *lost* with v3. I know one could simply read the source code, but I don't know ruby!

Anyways, excuse my digression, thank you.
