### ISSUE TITLE
Asset tag within variable as src

### ISSUE THREAD

**Issue by illycz** [envygeeks/jekyll-assets#453]
I'm trying use page variable like you mention here: https://github.com/envygeeks/jekyll-assets/issues/446#issuecomment-346349076

1. I have _assets/img folder where I have backgrounds folder within home.jpg image.
2. In Front matter I have set up:
`background: backgrounds/home.jpg`
3. In default.html layout I have:
`{% asset "{{ page.background }}" %}`
4. Jekyll serve get me this error:
`Liquid Exception: couldn't find file '/assets/images/backgrounds/home.jpg' Checked in these paths:`

Where is problem?

Thanks

**Comment by illycz** [comment]
As here: https://github.com/envygeeks/jekyll-assets/issues/454#issuecomment-347592478
I'm using now: `<img src="{{ assets[page.background].digest_path }}" alt="...">`

it has some impact on performance?

**Comment by gasparesganga** [comment]
No, I don't think so.
And please, this is not my repository, it's @envygeeks's. I answered your other question because it was pretty easy and all the information was already available in the documentation and other closed issues. Don't mention me (or anybody else who is not directly involved in this repository) in a random ticket, I don't think this is the proper way to use github ticket system.

**Comment by envygeeks** [comment]
What's the value of "page.background"?

**Comment by illycz** [comment]
Sorry, I mention you because I think it's related to your previous answer.

The value is relative path to image: backgrounds/home.jpg how I wrote above...

**Comment by envygeeks** [comment]
I'm gonna need to see the source or a reproduction, because we would never search within anything called "/assets" unless you add it, and even then, we would never spit out an absolute path, so there is something more going on that's gonna require a reproduction example.

**Comment by illycz** [comment]
A had one typo in Front Matter variable so, now everything working.

Thanks
