### ISSUE TITLE
How can I use asset within inline background image

### ISSUE THREAD

**Issue by illycz** [envygeeks/jekyll-assets#454]
How can I use asset to get image set in page variable like path for background image defined inline.

`<div class="..." style="background-image: url('');">`
How can I generate proper image url within `page.background` variable.

Thanks

**Comment by gasparesganga** [comment]
This is pretty straightforward, you can access the liquid drop directly and get the `digest_path`, see the [documentation](https://github.com/envygeeks/jekyll-assets#list).

**Comment by illycz** [comment]
Can you post example please, I'm Jekyll newbie.
Brackets inside brackets not working...

And img path defined in Front matter variable `background` must be relative to _assets/img which is one of default folders for images?

`<div class="..." style="background-image: url('{{ assets["{{page.background}}"].digest_path  }}');">`

Thanks

**Comment by gasparesganga** [comment]
You don't need *brackets inside brackets*, it's as simple as writing this:
`<div class="..." style="background-image: url('{{ assets[page.background].digest_path }}');">`

About the path, you can use the default folders or add your custom ones. Then you can safely use a path relative to any of those folders.

**Comment by illycz** [comment]
@gasparesganga It's working only when asset is generated already, like you mentioned here: https://github.com/envygeeks/jekyll-assets/issues/452

**Comment by envygeeks** [comment]
That's expected behavior.

**Comment by illycz** [comment]
@envygeeks so how can I use `asset` in this scenario?

**Comment by illycz** [comment]
Solution:
`<div class="..." style='background-image: url({% asset "{{ page.background }}" @path %});'>`

**Comment by bronislav** [comment]
@illycz 
```
{{ page.background | asset:"@path" }}
```

**Comment by illycz** [comment]
@bronislav your solution does not generate image to _site.

**Comment by envygeeks** [comment]
Yes it does.
