### ISSUE TITLE
Strip doctype, html and body tag

### ISSUE THREAD

**Issue by illycz** [envygeeks/jekyll-assets#455]
In default.html I have:

```
<!doctype html>
<html class="l-Site l-Site--{{page.layout}}  no-js" lang="{{ page.lang | default: site.lang | default: "en" }}" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
```

but final result starts with `<meta charset="utf-8">`

Before Jekyll Assets I haven't this problem...

**Comment by illycz** [comment]
Related issue: https://github.com/jekyll/jekyll/issues/4648#issuecomment-195425806

**Comment by illycz** [comment]
Generated page also missing body tag :(

**Comment by envygeeks** [comment]
Please provide the full source to your page (or a working example) that replicates the issue.

**Comment by illycz** [comment]
Here: https://github.com/JaroslavKorbel/jaroband

**Comment by devraj** [comment]
@illycz change `<!doctype html>` to `<!DOCTYPE html>` and the assets pipeline will validate markup

**Comment by envygeeks** [comment]
That leads me to believe it's a problem in our DOCTYPE checker, we should probably make it less strict.

**Comment by devraj** [comment]
@envygeeks I like the fact that it respects the standard but your call :)

**Comment by envygeeks** [comment]
I liked it too, but not everybody respects the standard that much, and it's more harm to our users than not, so I decided to go ahead and allow lowercase doctype, if the parser in the browser allows it at least.

**Comment by illycz** [comment]
I use html5boilerplate: https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L1

**Comment by envygeeks** [comment]
You should file a ticket with them and let them know their DOCTYPE is technically invalid.  As it should be `<!DOCTYPE html>` for HTML 5.  Hopefully they'll fix it, but master has already fixed this issue.
