### ISSUE TITLE
Gem is converting all `>` in scss files to `&gt;`

### ISSUE THREAD

**Issue by jeffblake** [envygeeks/jekyll-assets#457]
- [ x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [x ] I Am on OS X

## Description

As the title says, even though I am not using jekyll-assets for my css (I am using the default strategy outlined in the jekyll docs using the _sass dir), this gem seems to convert all `>` to `&gt;` in the source (viewed in Chrome)

I removed this gem from the Gemfile, bundled, and everything was back to normal.

**Comment by envygeeks** [comment]
Provide an example repository that this happens and, and an example of what it was before, and what it was after, what you are describing is so broad, I can name a thousand different reasons why this would happen, so it's an invalid report as it stands, it would be nice to know "before" with surrounding context and "after" with surrounding context.
