### ISSUE TITLE
Document on using magick with @pic and srcset

### ISSUE THREAD

**Issue by migueldemoura** [envygeeks/jekyll-assets#464]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [X] I Am on Linux
- [ ] I Am on OS X

## Description

Been trying to port some old alpha v3 code to the new syntax but stumbled upon some issues with using magick. The following describes what I've attempted to reach and what I've done to achieve it.

## Steps

- Old syntax on alpha v3
```
{% asset 'image.png'
    srcset:'magick:format=image/webp magick:resize=610 media="(min-width: 650px)"'
    srcset:'magick:resize=610 media="(min-width: 650px)"'
    srcset:'magick:format=image/webp magick:resize=440 media="(min-width: 480px)"'
    srcset:'magick:resize=440 media="(min-width: 480px)"'
%}
```

- New syntax attempt
```
{% asset 'image.png' @pic
    srcset:min-width='650' @magick:resize='610' @magick:format='image/webp'
    srcset:min-width='650' @magick:resize='610'
    srcset:min-width='0' @magick:resize='440' @magick:format='image/webp'
    srcset:min-width='0' @magick:resize='440'
%}
```
This is obviously not correct.

## Output

``` html
<picture>
    <source srcset="1.png 650w" media="(min-width: 650px)"></source>
    <source srcset="2.png 650w" media="(min-width: 650px)"></source>
    <source srcset="3.png 0w" media="(min-width: 0)"></source>
    <source srcset="4.png 0w" media="(min-width: 0)"></source>
    <img src="image.png">
</picture>
```
Also, and afaik, the `</source>` shouldn't be there.

## Expected

``` html
<picture>
    <source srcset="1.webp" type="image/webp" media="(min-width: 650px)">
    <source srcset="2.png" media="(min-width: 650px)">
    <source srcset="3.webp" type="image/webp" media="(min-width: 0)">
    <source srcset="4.png" media="(min-width: 0)">
    <img src="image.png">
</picture>
```

**Comment by envygeeks** [comment]
The `@` before any key name denotes a true.  Your value is never reaching it's destination.  The documentation should state this and point you to https://github.com/envygeeks/liquid-tag-parser which also provides documentation on these behaviors.

**Comment by envygeeks** [comment]
Aside from that the max-width decides how we run magick.  You cannot directly ship magick anymore.

**Comment by migueldemoura** [comment]
> Aside from that the max-width decides how we run magick. You cannot directly ship magick anymore.

So it's not possible to have a resize with a media query that's not the same as the resize? That's really useful for min-width: 0. As for the format conversion, how would one do it?

**Comment by envygeeks** [comment]
You'll have to build your own at that point. Because our responsive images are as basic as they get for now unless somebody is willing to sponsor the time it would take to get more advanced stuff.

**Comment by envygeeks** [comment]
I just realilzed after days of thinking of this that you can ship your own media, which will override ours.  The documentation should explain how to do this and even provide an example of how to do this.

**Comment by envygeeks** [comment]
Hey,

Can you spec out what you are wanting here in clear terms with examples.

**Comment by envygeeks** [comment]
If you can spec this out and hash out details with me in the next few days I can see what i can do for the next release, since this issue has been sponsored by Anomaly along with a couple other major feature requests.  So if you'd like to have something more advanced please do get back to me.

**Comment by migueldemoura** [comment]
@envygeeks, sorry for only replying now, had quite a few busy days.

The following is what I would like to be possible to do:

{% asset 'image.png' @pic
    srcset:'min-width="650" size="610" format="image/webp"'
    srcset:'min-width="0" size="440" format="image/png"'
%}

Output:

<picture>
    <source srcset="1.webp" type="image/webp" media="(min-width: 650px)"> 
    <source srcset="2.png" media="(min-width: 0)"> 
    <img src="image.png">
</picture>

Where, `size` contains the size to be passed to `magick-resize`, and `format` the format to `magick-format`. The syntax is merely an example.

**Comment by envygeeks** [comment]
After review, everything on that list is currently possible, except for the format changes, please file a ticket for that, but it won't be handled until 3.1 because it's a major feature and would require a lot of work, and even then it might not be done because the current format doesn't really support it, but I'll consider it.

Thanks!

**Comment by migueldemoura** [comment]
Hey @envygeeks, appreciate the update! It's no biggie that I can't use the format change, but could you provide an example on how to achieve this:

``` html
<picture>
    <source srcset="1.png" media="(min-width: 650px)"> <!-- Img size: 610px -->
    <source srcset="2.png" media="(min-width: 0)"> <!-- Img size: 440px -->
    <img src="image.png">
</picture>
```

This is the previous example but without the webp format change:

```
{% asset 'image.png' @pic
    srcset:'min-width="650" size="610" format="image/webp"'
    srcset:'min-width="0" size="440"'
%}
```
