### ISSUE TITLE
Inline JS and CSS still has a src/href attribute (3.x)

### ISSUE THREAD

**Issue by nateberkopec** [envygeeks/jekyll-assets#465]
`{% asset my_css_file @inline  %}` produces output like:
```
<style rel="stylesheet" type="text/css" href="/assets/css/my_css_file-b822053e8ad2f7fb9cc4862298c30f12e6aab7ac1f6e172a1716930f38336a7b.css">
Actual inlined content
</style>
```

`{% asset my_js_file @inline  %}` produces output like:
```
<script type="text/javascript" src="/assets/js/blazy-ff6d04965eeec36da3d94cc3bf2ea7d65ebd1ada39d069965efd2c6508b51832.js">
Actual inlined content
</script>
```

This effectively renders JS inlining useless, as the browser will still block and download the file. CSS seems unaffected and does not trigger an extra download.

**Comment by envygeeks** [comment]
CSS doesn't trigger one because there is no `href` attribute for `style`.  So it assumes it's a custom HTML5 attribute if you are in HTML5 and will throw a validator warning otherwise, script does because src is a literal part of it's spec.

**Comment by nateberkopec** [comment]
> script does because src is a literal part of it's spec.

[I do not think this is correct](https://stackoverflow.com/a/1056349). 

[Here is the relevant spec:](https://www.w3.org/TR/html5/scripting-1.html#inline-documentation-for-external-scripts)

> If there is a src attribute, the element must be either empty or contain only script documentation that also matches script content restrictions.

**Comment by nateberkopec** [comment]
Also I'll say it again, but the `src` attribute on script elements here is causing the browser to block and download the script, which *completely defeats the purpose* of inlining the script. This is easily reproducible in any browser.

**Comment by envygeeks** [comment]
Guy, you just mansplained my point, while trying to prove me wrong, while not realizing your issue was fixed, while banging on to prove me wrong when all you did was prove my pretty clear statements right. Calm down, and stop spamming me, your issue is fixed.

Thanks!

**Comment by nateberkopec** [comment]
Ah man, I'm so sorry! I just saw the "closed this" and didn't see that commit! Agh! Sorry for being such an asshole, I thought you just misunderstood me and closed the issue.
