### ISSUE TITLE
No HTML generated for SVG files

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#471]
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Description
SVG files do not generate an `<img>` tag in the HTML output anymore. This is something introduced with the very latest changes (possibly [here](https://github.com/envygeeks/jekyll-assets/commit/11f1adb198b358673c679ad9d28674cd4c7842b8#diff-0a107868599af9333b5347ec0cd5dfe9)), since it used to work just fine until v3.0.3.

## Steps
`{% asset filename.svg %}`

## Output
The asset is being processed into the output folder, but no HTML is printed out.

**Comment by envygeeks** [comment]
It is, because it's "image/svg+xml" which the regexp doesn't accept.

**Comment by kennedysgarage** [comment]
I am currently having this issue. I am using 3.0.5.
