### ISSUE TITLE
For loop with ImageMagik only the first iteration path

### ISSUE THREAD

**Issue by gasparesganga** [envygeeks/jekyll-assets#472]
- [x] I tried updating to the latest version.
  - [x] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [x] I Am on Linux
- [ ] I Am on OS X

## Description
This seems very related to the issue #449 about loops, but since it could be something completely different, I'll open a new one.
Everything works fine until ImageMagik enter into the games. The symptoms are basically the same: in a for loop, only the first element is being generated as HTML output.

Here is a [test repository](https://github.com/gasparesganga/test-jekyll-assets).

## Steps
    {% for i in (1..3) %}
        {% capture filename %}img/file{{ i }}.jpg{% endcapture %}
        
        
        
        {% asset '{{ filename }}' %}
        
        
        {% asset '{{ filename }}' magick:resize='300' %}
    {% endfor %}

## Output
    
        
            
            <img src="/assets/img/file1-e2782b1311548ee453d30057d355f356d3610de203b4150d29c9b8c11b4fee06.jpg">

            
            <img src="/assets/8b8267-d7a8cedee81e1cf60a58410ec010c3bb396a2f315f9487006d695f52cb41e794.jpg">

        
            
            <img src="/assets/img/file2-0fa49a57547760216a8be1b858668ea65cc4e8fcfdf11cc54ffbc5be3db4b7f8.jpg">

            
            <img src="/assets/8b8267-d7a8cedee81e1cf60a58410ec010c3bb396a2f315f9487006d695f52cb41e794.jpg">

        
            
            <img src="/assets/img/file3-61b9272b795a5ec5fbbdfaff404ff53b7ebbc8ce9e847c248914f5ef4959c856.jpg">
            
            <img src="/assets/8b8267-d7a8cedee81e1cf60a58410ec010c3bb396a2f315f9487006d695f52cb41e794.jpg">

**Comment by envygeeks** [comment]
I am unable to replicate this issue, also, you should stop using `{% capture %}` where you should be using `{% assign %}`, Capture is meant to be used with multi-line assignments AKA captures, whereas you are simply just creating a variable.

**Comment by envygeeks** [comment]
Please provide a repository that can replicate this issue for you so that I can shim it.

**Comment by gasparesganga** [comment]
Thank you for the `{% capture %}` advice, you're absolutely right.

About the test repository, the link is in already in the first message, I'll copy/paste it here too: https://github.com/gasparesganga/test-jekyll-assets
In order to keep things easily trackable for you, I put all the relevant code into `_layouts/default.html` file.

**Comment by envygeeks** [comment]
Thanks. I'll take a look today or tomorrow.

**Comment by nielsenramon** [comment]
@envygeeks @gasparesganga Would there be any workaround for the time being? Running into the same issue with the following code:

```
  {% for picture in site.data.pictures %}
      {% asset '{{ picture.path }}' magick:resize='400' %}
    {% endfor %}
```

Live example here: http://marble.nielsenramon.com/

As you can see, all the images are the same. When clicking on one it opens the correct image which is in the same for loop without image magick.

**Comment by benben** [comment]
I ran into this problem too! Would love to see a workaround.
