### ISSUE TITLE
Messing with my script text/template

### ISSUE THREAD

**Issue by borisschapira** [envygeeks/jekyll-assets#478]
- [x] I tried updating to the latest version (3.0.5)
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [x] I Am on OS X

## Description

One of my pages contains an inline `<script>` containing a template:

```
  <script id="algolia__template" type="text/template">
    <article id="content" class="algolia__result post" itemscope itemtype="https://schema.org/BlogPosting">
      {% raw %}{{#posted_at}}{% endraw %}
      <header>
          <span class="p-date algolia__result-date">{% raw %}{{ posted_at_readable }}{% endraw %}</span>
      </header>
      {{/posted_at}}
      <h1 class="post-title"><a class="algolia__result-link" href="{% raw %}{{ full_url }}{% endraw %}">{% raw %}{{{ _highlightResult.title.value }}}{% endraw %}</a></h1>
      <div class="algolia__result-text post-content">{% raw %}{{{ _highlightResult.text.value }}}{% endraw %}</div>
    </article>
  </script>
```

When jekyll-assets is not loaded, this render like this:

```
  <script id="algolia__template" type="text/template">
    <article id="content" class="algolia__result post" itemscope itemtype="https://schema.org/BlogPosting">
      {{#posted_at}}
      <header>
          <span class="p-date algolia__result-date">{{ posted_at_readable }}</span>
      </header>
      
      <h1 class="post-title"><a class="algolia__result-link" href="{{ full_url }}">{{{ _highlightResult.title.value }}}</a></h1>
      <div class="algolia__result-text post-content">{{{ _highlightResult.text.value }}}</div>
    </article>
  </script>
```

When jekyll-assets is loaded, it renders like this

```
  <script id="algolia__template" type="text/template">
    <article id="content" class="algolia__result post" itemscope itemtype="https://schema.org/BlogPosting">
      {{#posted_at}}
      <header>
          <span class="p-date algolia__result-date">{{ posted_at_readable }}
      
      
      <h1 class="post-title"><a class="algolia__result-link" href="{{ full_url }}">{{{ _highlightResult.title.value }}}
      <div class="algolia__result-text post-content">{{{ _highlightResult.text.value }}}
    
  </script>
```

Is it possible that Jekyll Assets mess with my `text/template` script ending tag, even when I don't use it there (the script code is inlined directly into my Jekyll layout) ?

**Comment by envygeeks** [comment]
Please provide an example repository with replication steps, and an example configuration like yours, so that it can be shimmed.

Thanks

**Comment by borisschapira** [comment]
@envygeeks sample repo with the bug: https://github.com/borisschapira/jekyll-bugs/releases/tag/jekyll-assets-478

Replication steps:

* Install
* Serve

The code is in the only post and not served correctly.

**Comment by envygeeks** [comment]
Unfortunately there isn't much I can do about this, it's a LibXML problem (and Nokogiri.) You can however prevent it from happening if you don't use some of our features:

```
assets:
  plugins:
    img:
      searcher: false
```

This will disable the logic we have to give you Markdown previews.
