### ISSUE TITLE
Is there an option to disable the long file names?

### ISSUE THREAD

**Issue by publicarray** [envygeeks/jekyll-assets#486]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [x] I Am on OS X

## Description

Is there an option to disable the long file names?
Thanks

## Output

`index-3db0e6f01d332e8d9341aab4bbdf42089a6c9ccec4fbf88095f7b5b772588c59.css`

## Expected

`index.css`

**Comment by envygeeks** [comment]
There isn't, by design.  The most you can do is disable digesting, which should be in the documentation.  In the future please remember this tracker is for bugs only.

**Comment by publicarray** [comment]
Thanks for your speedy response.

> There isn't, by design. The most you can do is disable digesting

Yes that is what I want:

```
assets:
  digest: false
```

>  should be in the documentation

While the digest setting is not documented on Github it is documented [here](https://envygeeks.github.io/jekyll-assets/#configuration).  I assumed the [configuration example on Github](https://github.com/envygeeks/jekyll-assets#configuration) was with a list of all available options and the one on the website was a usage example so I did not look close enough.
Would you be so kind to update the readme? thanks

**Comment by envygeeks** [comment]
No. It's an Easter egg configuration that is not encouraged.
