### ISSUE TITLE
Help with Loops and Filtering

### ISSUE THREAD

**Issue by edwardessing** [envygeeks/jekyll-assets#492]
Hey, wondering how the following lines:
`{% for image in site.static_files %}`
`{% if image.path contains 'assets/selected' %}`
Would be converted to suit the jekyll-assets plugin

Thank you!

**Comment by envygeeks** [comment]
Hey!

This ticket system is for bugs only.  We do not provide design advice, Liquid advice, or anything past documentation, and support of the software if there is a bug related to the software.  It's a policy to never consult for free.

Thanks!
