### ISSUE TITLE
Liquid Exception: Invalid option: harmony

### ISSUE THREAD

**Issue by funkenstrahlen** [envygeeks/jekyll-assets#494]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [ ] I Am on Linux
- [x] I Am on OS X

## Description

Including Javascript via liquid asset tag creates liquid exception `Liquid Exception: Invalid option: harmony`

## Steps

* Include Javascript via liquid tag like this: `{% asset app.js %}`
* Run `JEKYLL_ENV=production jekyll build`
* Error `Liquid Exception: Invalid option: harmony`

Interesting: The error does not happen when I run `JEKYLL_ENV=development jekyll serve`.

## Output

```sh
JEKYLL_ENV=production jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
      rouge (< 4, >= 1.7)
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/funkenstrahlen/Projects/funkenstrahlen.de/_config.yml
            Source: /Users/funkenstrahlen/Projects/funkenstrahlen.de
       Destination: /Users/funkenstrahlen/Projects/funkenstrahlen.de/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Invalid option: harmony in /_layouts/default.html
```

The line making problems is `{% asset app.js %}`. When I remove it, it does not create the error.

## Expected

No error.

**Comment by envygeeks** [comment]
Please provide the full trace, as there is nothing called "harmony" in any of our source.

**Comment by funkenstrahlen** [comment]
Docs of uglifier about harmony mode: `# Enable ES6/Harmony mode (experimental). Disabling mangling and compressing is recommended with Harmony mode.`

So first: This seems to be experimental. Second: `jekyll-asset` does enable harmony and compression at the same time.

This does not seem the source of my issue though.

**Comment by funkenstrahlen** [comment]
@envygeeks jekyll-asset does call `uglifier` with the harmony option. So its your code passing the invalid option.

**Comment by envygeeks** [comment]
harmony mode for "js" is something *you* can disable, so if it were the problem, this would immediately be a WONTFIX.  I doubt that is the issue unless Uglifier either recently updated and removed the option, or you are using a very old version of uglifier.  Or you are on node and it recently removed the option (I don't really keep up with node tbh.)

A trace as requested will point out if that is the problem, and where it originates from.

**Comment by funkenstrahlen** [comment]
I think I discovered something: 

I currently have `uglifier` installed in version `2.7.2`. This is very old. Probably this old version is missing the `harmony` option and therefore causing the liquid exception.

However it does install this old version even when I run `bundle update` with this `Gemfile`:

```
gem 'jekyll'
gem 'jekyll-paginate'
gem "jekyll-assets", group: :jekyll_plugins
gem 'jekyll-minify-html'

gem 'kramdown'
gem 'rouge'
gem 'sass'
gem 'uglifier'
gem 'mini_magick'
```

Do you know why?

**Comment by envygeeks** [comment]
Because you are not on Sprockets 4.x as recommended in the documentation.

**Comment by funkenstrahlen** [comment]
I think I simply have to cleanup my Gemfile. Thank you for your help!
