### ISSUE TITLE
Assets with a "-" return error

### ISSUE THREAD

**Issue by tedserbinski** [envygeeks/jekyll-assets#497]
## Description

I am trying to upgrade to v3.0.7

I am running into an error with assets that have a "-" in the file name.

## Steps

- Create an asset with a "-" in it like file-name.jpg
- Try and compile

## Output

```sh
Liquid Exception: no implicit conversion of Symbol into Integer
```

Thanks!

**Comment by envygeeks** [comment]
Please provide a trace.  That exception is non-useful. Thanks.

**Comment by tedserbinski** [comment]
Hmm I'm having trouble repeating this now. Not sure what I changed. Looks like might have been an ASCII vs UTF8 copy/paste issue.

Let me dig into more.

**Comment by tedserbinski** [comment]
I think a bad _config was causing the issue. I had CDN under the 2.x syntax instead of 3.x syntax.

Strange how that went to the filename as the error.

Working now!
