### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by zininen** [envygeeks/jekyll-assets#498]
- [ ] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
- [x] I Am on Bash on Windows 10
- [ ] I Am on Linux
- [ ] I Am on OS X

I just installed jekyll-assets (gem install, bundle update) . I cannot get image handling to work by using any of the examples, such as

```
{% asset img.png
    srcset:width="400 2x"
    srcset:width="600 1.5x"
    srcset:width="800 1x"
      %}
```

While running  "JEKYLL_ENV=production bundle exec jekyll build --watch --incremental" I just get 
"Liquid Exception: incompatible character encodings: ASCII-8BIT and UTF-8 in "/mnt/e/_dev/_source/site/_posts/2018-02-09-test.markdown"

If I remove the example code above, jekyll works, apparently the jekyll-assets does not have anything to process.

Mind you, I have to use ffi-1.9.18 as the newer version ffi-1.9.21 does not compile in Windows 10 developer mode bash á la Ubuntu.

Either I am doing something wrong or there is a bug affecting only Windows environment somewhere. My guess is that it is in jekyll-assets as this was the last package I have installed. Could be something else.

Here is trace:
--

```
JEKYLL_ENV=production bundle exec jekyll build --watch --incremental --trace
Configuration file: /mnt/e/_dev/_source/site/_config.yml
            Source: /mnt/e/_dev/_source/site
       Destination: /mnt/e/_dev/_deploy/
 Incremental build: enabled
      Generating...
                    Asset caching is disabled by configuration. However, if you're using proxies, a cache might still be created.
  Populating LSI...
Rebuilding index...

  Liquid Exception: incompatible character encodings: ASCII-8BIT and UTF-8 in /mnt/e/_dev/_source/site/_posts/2018-02-09-test.markdown
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `join'
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:103:in `render'
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
  /var/lib/gems/2.4.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:123:in `render_liquid'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:76:in `render_document'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/renderer.rb:62:in `run'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:453:in `block (2 levels) in render_docs'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:451:in `each'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:451:in `block in render_docs'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:450:in `each_value'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:450:in `render_docs'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:190:in `render'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/site.rb:73:in `process'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/command.rb:28:in `process_site'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/commands/build.rb:65:in `build'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/commands/build.rb:36:in `process'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /var/lib/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /var/lib/gems/2.4.0/gems/jekyll-3.7.0/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
```

**Comment by envygeeks** [comment]
The bug is Windows. "Bash on Windows" should be defaulting to UTF-8 like Linux does, but I guess that would be impossible if you are writing from Windows. We are not mentioned anywhere in this trace, why is there an assumption that we are responsible?

**Comment by zininen** [comment]
> We are not mentioned anywhere in this trace, why is there an assumption that we are responsible?

Well, this happened while following instructions given in README.md of jekyll-assets after installation of the plugin, so my best guess was that issue is connected.  And yes, if  instructions of a plugin cause undesired effects, then those instructions are responsible, unless there is a reservation "sorry, do not try this environment x, evenif the main application works in it".

But then, I have no knowledge what Windows 10 bash really does and whether there is a bug in Windows 10 implementation of Ubuntu bash regarding that.

Still, I am not fully satisfied with the explanation. I have checked the encoding of the file, and it definitely is UTF-8 without BOM.  It was kind of funny, that other plugins I use do understand expression {% even in Win10 Ubuntu bash , but here I run into error. Therefore I was almost certain that this would be a user error on my behalf.

OK,  I understand that jekyll-assets is not supported in Windows 10 Ubuntu bash flavor. Responsive images are necessity nowadays. 

Will be moving on.

**Comment by envygeeks** [comment]
I asked a simple question. There is no need to get defensive, as my question was a standard diagnostic question that any programmer, or systems person would ask with such a broad explanation.  This has nothing to do with understanding "{%".  If you do not wish the bug to be fixed, or to provide more information that is necessary, that is all that need be said.

I wish you the best.
