### ISSUE TITLE
CSS asset file not being copied to assets folder

### ISSUE THREAD

**Issue by tedserbinski** [envygeeks/jekyll-assets#499]
So this is strange behavior but I can repeat it.

I have an external CSS file that is loading an asset with asset_url(). 

When I compile the site, the asset is NOT in the _site/assets folder.

If I use that same asset in a html file, it loads properly and is copied to _site/

In the both cases, the URL to the asset is exactly the same. But the asset is only copied to _site/ if it is appears in a html/markdown file. Any assets in CSS are NOT copied over.

You can see the source code to my site here:
https://github.com/tedserbinski/www-tedserbinski-com/tree/v2018-update

The asset in CSS is _assets/css/custom/_page-home.scss as "bg.jpg"

**Comment by tedserbinski** [comment]
Strange, I've tried with other images and they seem to work in CSS. Just something about this very particular image. 

Tried different extensions, renaming it, etc. Hmm.

**Comment by tedserbinski** [comment]
Ok, seems to be something related to the caching layer.

When I switch caching: type: memory   file is properly copied to _site/ and loads.  When I move the file to another folder it loads.

**Comment by tedserbinski** [comment]
I think this was a cache bug. I delete .jekyll-cache folder and it loaded properly.

Ugh what a morning tracking that down :-)

**Comment by envygeeks** [comment]
If it happens again and you can reproduce it, please do provide a trace, we don't generally manage our own cache past Proxies, but a trace would help us help Sprockets fix any bugs that might exist, as caching is hard.

**Comment by nadnoslen** [comment]
1. I had this exact same thing happen while using `background-image: asset_url("...")` in once of my scss files. 
1. I ended up hacking around it temporarily by using the `background-image: url(asset_path("..."))` helper instead.  Suddenly things worked.
1. I switched back to `background-image: asset_url("...")` and now it works again.

I came to report this problem and found @tedserbinski's  issue.  I too cannot reproduce.

### Background 

The only thing that has changed for me is recently swapping Ruby versions with RVM.  I was using `Ruby-2.3.6`, upgraded to `Ruby-2.3.7`, bundled my site, and things broke.
