### ISSUE TITLE
Allow overriding image src property

### ISSUE THREAD

**Issue by migueldemoura** [envygeeks/jekyll-assets#500]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.

- [ ] I Am on Windows
- [ ] I Am on Bash on Windows
- [X] I Am on Linux
- [ ] I Am on OS X

## Description

The best way of achieving image lazy loading is by replacing the src property with thumbnail and moving the actual full image path to another like data-src. Then javascript is used to replace src with data-src when the image is to be loaded.

This isn't possible afaik with jekyll assets as you can't override the src property or ask for it to be set at a different property.

## Output

``` html
<img src="image.png">
```

## Expected

``` html
<img src="thumb.png" data-src="image.png">
```

**Comment by envygeeks** [comment]
I feel like this is complex and out of scope. And this is a classic case of why plugins exist, because to me this really feels like I wish to keep convention over configuration. We also provide numerous other ways to do this as well.

**Comment by migueldemoura** [comment]
I was scratching my head around how to express this elegantly, and I have to agree with you.

> We also provide numerous other ways to do this as well.

Could you elaborate? How would I accomplish the lazy load? Thanks!

**Comment by envygeeks** [comment]
The documentation provides ways for you to manually build out HTML and get the same data we have access to.  On top of that, it also provides an example of a plugin that would give you access to the full Ruby scope.

Thanks!

**Comment by maesitos** [comment]
A workaround would be:

```erb
<img data-src="{% asset image.png @path %}">
```

But it goes against the Liquid philosophy I guess.
