### ISSUE TITLE
Tag parsing order issue - ImageMagick options seem processed wrong.

### ISSUE THREAD

**Issue by iceboundflame** [envygeeks/jekyll-assets#503]
- [x] I tried updating to the latest version. (3.0.7)
- [x] I Am on macOS

## Description

I have image asset tags that generate thumbnails using this combination of ImageMagick tags. It's important that the resize happens before the cropping.

```
{% asset '{{ asset }}' alt:"{{ img.title | xml_escape }}"
   magick:resize=300x300^ magick:gravity=center magick:crop=300x300+0+0 magick:quality=90 %}
```

However, some images sporadically seem to be cropped from the full-resolution image, instead of downsizing and then cropping, suggesting ImageMagick got the arguments in the wrong order. It happens consistently on my site when the config is set to `img: { integrity: true }`: under the default configuration, it was doing the wrong thing in `JEKYLL_ENV=production` but fine in development.

I can try to get a minimum working example to repro the issue, however it would take some time because I'm noticing this as part of my full site right now.

**Comment by envygeeks** [comment]
This is expected, and known behavior. Our arguments are non-positional, even when parsed.

**Comment by iceboundflame** [comment]
Thanks for the quick reply and confirmation!

I took a quick look at the code to try and figure out the problem. AFAICT, Liquid::Tag::Parser is actually ordering args correctly, because in Ruby >1.9, hashes maintain insertion order. However, in [jekyll/assets/plugins/proxy/magick.rb](https://github.com/envygeeks/jekyll-assets/blob/master/lib/jekyll/assets/plugins/proxy/magick.rb), the order is ignored. Instead, each of the `magick_*` methods are invoked, in an order determined by `Object#private_methods(true)`. I'm not sure why this order would be unstable. But it suggests possible routes to fix:

1) Instead of using private_methods, use the user-provided order of magick: arguments, by iterating over the "magick:X=Y" hash and calling the corresponding magick_X functions. This should give the user control over the order.
2) Alternatively, define the order of arguments in an array in the magick proxy, and always call it in that order. But some people might want to resize then crop, and others might want to crop then resize.
3) Define a different format of magick arguments, and store them as an array rather than a hash. This is the most drastic but gives ultimate flexibility, especially if you decide to support proxying arbitrary ImageMagick options in the future (there's a [huge range of filters/transforms available](https://www.imagemagick.org/script/convert.php)). It is possible that one would want to use the same transformation twice, e.g. resize, apply an effect, then resize again, which this approach would enable. I don't personally need other filters at the moment but it is something to think about.

I suggest the first or second approach as a stopgap, but the third seems to be a nice longer-term solution.

**Comment by iceboundflame** [comment]
Thanks @envygeeks! You rock.
