### ISSUE TITLE
magick tag modification causes file duplication in the assets folder

### ISSUE THREAD

**Issue by richardgazdik** [envygeeks/jekyll-assets#506]
I'm using the magick tag to resize my images in the assets folder:

`{% asset src magick:resize=144 alt='thumb-11'   %}`

Any modification on the magick tag causes file duplication in the assets folder. It seems like the old image files are also copied from the cache rather than keeping only the newest version of the image in the assets folder.

I have one more magick related question: Is there a way to use a folder for the generated images instead of using the assets root for storing them?

**Comment by envygeeks** [comment]
Please fill out the form that was given when filing the ticket, and provide more information, or a repository that can replicate the issue.  Since this is tested explicitly a broad ticket does no help.

Thanks!

**Comment by envygeeks** [comment]
This issue is being closed for lack of response.
