### ISSUE TITLE
Asset Liquid Tags do not point to the correct URL when used with jekyll-multiple-languages-plugin

### ISSUE THREAD

**Issue by james7132** [envygeeks/jekyll-assets#507]
- [ ] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Description
The plugin interacts correctly with [jekyll-multiple-languages-plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin) in that it doesn't create a new set of assets for each translated version of the site. However, the `{% asset  ... %}` liquid tag behaves like it should have: instead of generating the correct `/assets/styles-{...}.css` link it points to `/es/assets/...` instead, which breaks all extra links to CSS/JavaScript/etc.

## Steps

- Include both jekyll-assets and jekyll-multiple-languages-plugin
- Add a few assets and link them using the liquid tag.
- Configure for multiple languages (`language: ["en", "es", "fr"...]`).
- Build.
- Check generated HTML at liquid tag site.

## Output
The `{% asset  ... %}` liquid tag prepends a language specifier to the link: `/es/assets/...`.

## Expected
Since the assets output is only generated once for the entire site, it should consistently point only to the original `/assets/...` directory, regardless of what language that is being used.

**Comment by envygeeks** [comment]
If my software outputs correctly without their software installed, then it's not my bug. It's not my job to integrate with them, the order of integration you are requesting is backwards.  If they alter any of my classes (not saying they do,) or any of the Jekyll settings, in a way that affects the integrity of my software, it is their bug, and their problem to fix.

Sorry.

**Comment by james7132** [comment]
If others are looking for a potential fix for this issue, there's a [1-2 line change](https://github.com/HouraiTeahouse/jekyll-assets/blob/master/lib/jekyll/assets/utils.rb#L245) that can be done to fix this.

**Comment by maesitos** [comment]
Pull request fixing this use here: https://github.com/envygeeks/jekyll-assets/pull/601

**Comment by maesitos** [comment]
Pull request fixing this issue https://github.com/envygeeks/jekyll-assets/pull/602
