### ISSUE TITLE
[Bug] Build error(related to uglifier gem)

### ISSUE THREAD

**Issue by bananaappletw** [envygeeks/jekyll-assets#511]
- [X] I tried updating to the latest version.
- [X] I Am on Linux

## Description

Thanks for the great work of `jekyll-assets`.

I am using the latest `jekyll-assets` gem on my jekyll project.

When I build the website by `JEKYLL_ENV=production jekyll build` command.

Error prompt `require': cannot load such file -- uglifier (LoadError)`

After that, I tried to fix the error. I added uglifier as runtime dependency.

Then try again.

Error prompt `jekyll 3.7.3 | Error:  Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).`

I try to read `lib/jekyll/assets/config.rb`.

There a `harmony` flag to configurate, but it seems not working.

```ruby
compressors: {
  uglifier: {
    comments: false,
    harmony: Utils.new_uglifier?,
  },
},
```

Even I replaced `Utils.new_uglifier?` to `true`.

I think solution is to initialize Uglifier with harmony flag at `lib/jekyll/assets/compressors/uglify.rb`.

Thank you.

**Comment by timrogers** [comment]
It looks to me that we're not actually passing any options in to `Uglify`, our `Sprockets::UglifierCompressor` subclass, in `lib/jekyll/assets/compressors/uglify.rb`, which means that whatever options you put in the config won't actually be listened to.

Prior to https://github.com/envygeeks/jekyll-assets/commit/218f5ee98ad2f39860a58111336f5049ee23f341, it looks like we did this, but it's not apparently broken.

I'm not sure how to fix it within the new architecture. We don't seem to have access to the configuration in the scope where the Sprockets compressor is registered.

**Comment by timrogers** [comment]
I've written a fix. Coming right up!

**Comment by bananaappletw** [comment]
@timrogers 
I totally agree with you.
