### ISSUE TITLE
Magick example that passes a value that is not a preset

### ISSUE THREAD

**Issue by danielnashnz** [envygeeks/jekyll-assets#513]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [x] I Am on macOS

## Description

I can't find a single example anywhere of passing a value from a jekyll-asset into the "ImageMagick" plugin other than the Filter at https://github.com/envygeeks/jekyll-assets#filter
... which for me fails

## Steps

- apply the Liquid tag: {{ thumb | asset:"@magick:2x magick:quality:92" }}

## Output

```sh
 Liquid Exception: `mogrify -quality {:"92"=>nil} -strip /var/folders/y7/gyq_j18d17d879wpccrrh015rxztx_/T/mini_magick20180315-60374-lclbe0.jpg` failed with error: mogrify: invalid argumentfor option '{:"92"=>nil}': -quality @ error/mogrify.c/MogrifyImageCommand/5749. in /_layouts/master_episode.html
```

## Expected

Tag with ref to transformed asset

**Comment by danielnashnz** [comment]
This syntax with "=" rather than ":" for the magick param values worked for me:
{% asset '{{thumb}}' magick:resize=96x48 magick:quality=50 magick:crop=48x48+0+0 @data %}

**Comment by envygeeks** [comment]
Quote the argument as a whole, per the Liquid documentation. I feel this is out of scope for me as I am not here to teach you how to use Liquid, that is their job.  I am only here to build a plugin that works *with* Liquid.  Those filters are being removed soon anyways so I don't feel it's necessary to clarify their documentation.

**Comment by envygeeks** [comment]
As for the ":" vs "=" every one of our examples demonstrates that, and we even provide a mini documentation section that explains it, and points to a larger set of documentation for the parser.

**Comment by danielnashnz** [comment]
Thanks, but I'm not sure your response answers the problem.

The example from the jekyll-assets README documentation that I quoted (and was attempting to get working) already had the argument quoted "as a whole", i.e.:
```{{ thumb | asset:"@magick:2x magick:quality:92" }}```

It appears that the second colon separator in the magick parameter (i.e. '92' - the one that passes a value) is the problem (see the "Output" quoted in the Issue description above).

**Comment by envygeeks** [comment]
Right now this seems like a PEBKAC issue; we document that `magick:quality:92` is not valid form for our arguments. It's in the documentation at https://github.com/envygeeks/jekyll-assets#arguments and even link to the parsers documentation itself which explains this in further detail, including examples of ways the parser is designed to make arguments easier.

**Comment by jonchang** [comment]
https://github.com/envygeeks/jekyll-assets/blob/9e36cf685932f78f92c9c2dcdb5f552c9f714e5a/README.md#filter suggests that `{{ src | asset:"@magick:2x magick:quality:92" }}` is indeed a valid way to pass arguments. I encountered this issue too and was misled by this bit of documentation.
