### ISSUE TITLE
Use Jekyll-assets to include html files

### ISSUE THREAD

**Issue by jeremylynch** [envygeeks/jekyll-assets#517]
`include_relative` is useful in jekyll however it can't be used in layout files or from the _includes directory. 

Jekyll assets could potentially solve this issue if it rendered .html files correctly. At present they are being rendered in an iframe. 
```
{% asset partial.html %}
```

**Comment by envygeeks** [comment]
Use `{% include %}`?  I feel this is out of scope for Jekyll Assets, we are not a content pipeline, we are an asset pipeline, and partials are not strictly an asset in the sense of what we would support. What benefit would this provide for me to support this?

**Comment by envygeeks** [comment]
This issue has been closed due to lack of response.
