### ISSUE TITLE
Can't find any asset

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [envygeeks/jekyll-assets#523]
https://pastebin.com/vzdz0GQk

my about.md looks like this

---
layout: page
title: About
permalink: /about/
---
{% asset mycss.css %}

My folderstructure looks like this https://pastebin.com/vQvXHNyq . So what's wrong, why can't he find any assets?

**Comment by envygeeks** [comment]
Hello, this is a PEBKAC issue, see https://github.com/envygeeks/jekyll-assets#configuration, look at the "sources" section for how the structure should be setup.  Past that I do not provide support for people's personal sites.

Thanks!
