### ISSUE TITLE
README.md - `compression: true` Not Working With Uglifier

### ISSUE THREAD

**Issue by nadnoslen** [envygeeks/jekyll-assets#524]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [ ] I Am on Linux
- [x] I Am on macOS

## Description

My javascript _minification_ does not seem to be happening.  My js files are all concatenated together but the minify step is being skipped.  Notice that my css files are compressed.

I believe the README.md file for this project might be misstating the `compression: true` setting.

## Steps

I was depending on the `_config.yml` setting:

```yams
assets:
  compression: true  # found in this project's README.md
  ...
  compressors:
    uglifier:
      comments: false
      harmony: true
```

...followed by my build commands:
```bash
$ JEKYLL_ENV=production bundle exec jekyll clean
$ JEKYLL_ENV=production bundle exec jekyll b
```
...to actually minify my javascript files that I've concat'd together.

## Output

My js compression is not happening.  CSS is compressed.

### Note

I'm using Uglifier and have set `harmony: true` (see above).

## Expected

Javascript files to be compressed.

### My Fix

I saw another closed issue in this project where someone had their compression settings set to:

```yams
assets:
  compress:
    css: true
    js: true
```
...and upon doing that in my case (removing the `compression: true` altogether) my js asset was completely minified as I desired.

I also noticed that if I completely omit the `compress: ...` configuration my assets compress properly when built for production and are left uncompressed when built for dev.

## Summary

* README.md probably needs updating?
* The logic around supplying compression settings to uglier might need to be examined.  I'd do it, but I'm swamped.

**Comment by envygeeks** [comment]
This is a duplicate.

**Comment by nadnoslen** [comment]
Kripes.  Sorry about that @envygeeks.
