### ISSUE TITLE
@path broken in 3.0.10

### ISSUE THREAD

**Issue by grauschnabel** [envygeeks/jekyll-assets#531]
- [X] I tried updating to the latest version.
  - [X] I can't, there is an issue.
- [X] I Am on Linux
  - [X] Arch Linux

## Description

I just updated to 3.0.10 (from 3.0.8), via `bundle update` and `bundle exec jekyll serve -low` just gives:

`jekyll 3.7.3 | Error:  couldn't find file 'true' in `index.md'`

The `_layout/home.html`, used in the index.md defines a `style="background-image: url({% asset 'backgrounds/{{ page.image }}' @path %});"` which worked fine before the `bundle update`.  Now I get this message, and `git status` doesn't find any other changes then this upgrade. 

When I edit my `Gemfile.lock` and set jekyll-assets back to 3.0.8, and I run `bundle install`,  my `bundle exec jekyll serve -low` works as before and gives me fine results as expected.

**Comment by envygeeks** [comment]
If your repository is open source please link to it and the source code portion so it can be shimmed, if it's not please provide a debug output, and a repository to duplicate the issue so that a hotfix can be released today, thanks!

**Comment by grauschnabel** [comment]
I tried to reproduce this with a minimal jekyll build but there it seems to work. I don't relly know what is breakting the @path from working.  when I remove it in the described example above, jekyll builds fine (but wrong html of course). puting it in again it search for the file 'true' instead of the given file, but in 3.0.8 it worked fine.

**Comment by grauschnabel** [comment]
ok, the interesting thing is that I had after the `@path` also `@magick:level:\"0%,100%,2.0\"`.  Changing that to `@magick:level:'0%,100%,2.0' makes it work again (with 3.0.11).  I don't really know why but it works.

**Comment by envygeeks** [comment]
`@magick:level:'value'` is invalid in it's entirety. That should be `magick:level='value'`

**Comment by grauschnabel** [comment]
but it works.  I changed my things to your notation, and it's fine too.
