### ISSUE TITLE
Add plugin examples.

### ISSUE THREAD

**Issue by grauschnabel** [envygeeks/jekyll-assets#532]
Hi there,

I try to use jekyll-assets also in another module to get the right path for an compiled asset.  How could the code {% asset 'myfile.jpg' @path %} look inside another ruby file?

```
require 'jekyll-assets'
...
```

what next?

I just found [Building your own plugins](https://github.com/envygeeks/jekyll-assets#building-your-own-plugins) but I cannot figure out how this is working.  Maybe you could add some examples for the usage?

**Comment by envygeeks** [comment]
The whole plugins folder is an example of how our plugin system works.

**Comment by envygeeks** [comment]
I'm thinking of linking `examples` to `plugins` from the root.  Or are you looking for other types?
