### ISSUE TITLE
Getting different path for same asset when using @path or filter

### ISSUE THREAD

**Issue by xaralis** [envygeeks/jekyll-assets#536]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
- [x] I Am on macOS
- [x] I'm on Docker
  - [x] I understand Docker may be unsupported.

## Description & steps

I'm trying to get asset path for an image which is using ImageMagick. It works OK, there is just one thing I don't understand. I suppose it's just my mistunderstanding. I'm having two asset tags which are basically the same. The only difference is that in second case, I would like to get the image path:

```
{% asset '{{ article.image }}' magick:resize="263x147" alt='{{ article.title }}' %}
{% asset '{{ article.image }}' magick:resize="263x147" @path %}
```

Trouble is, the second tag gets different asset URL and I indeed verified that the same image is for some reason built and resized twice under different filenames.

When I try to output the image multiple times the same way, I'm getting expected results:

This outputs two same path strings:
```
{% asset '{{ article.image }}' magick:resize="263x147" @path %}
{% asset '{{ article.image }}' magick:resize="263x147" @path %}
```

This ouputs two image tags with same `src` attribute:
```
{% asset '{{ article.image }}' magick:resize="263x147" alt='{{ article.title }}' %}
{% asset '{{ article.image }}' magick:resize="263x147" alt='{{ article.title }}' %}
```

## Expected

I would expect, that the asset path is the same as it's the same image with same transformation.

**Comment by envygeeks** [comment]
This is both expected and designed behavior.  The system is disaware of what is a proxy and what isn't a proxy, and proxies do not create their own files, they only ask the upper layer to create on for it, so it uses the entire argument hash to create a file hash to proxy with, if you change any of the arguments, the hash will change.

I see no reason to change this behavior as it decreases performance considerably.
