### ISSUE TITLE
Asset not compiled unless referenced via {{ asset }}

### ISSUE THREAD

**Issue by cameronmcefee** [envygeeks/jekyll-assets#543]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
- [ ] I Am on macOS
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported.

## Description

I suspect this may be by design, but when I only reference an asset via the asset collection, it isn't copied to the asset folder. I must include it somewhere using the `asset` tag.

To work around this, I add a page that includes the complete asset list to ensure everything is copied, and then delete the page prior to deploying.

```
{% for asset in assets -%}
    {% asset '{{ asset[0] }}' %}
{%- endfor %}
```

## Steps

- Add an image to the asset folder
- Reference it somewhere using `{{ assets[myasset.jpg].digest_path }}`
- delete `_site` and then restart the server.

## Output

The asset will not be copied.

## Expected

The asset should be copied to the asset folder.

**Comment by envygeeks** [comment]
This is by design because `assets` is just a reference point.  As for working around it, there is no need to do that, you can do `precompile: []` just like on Rails and have those assets found and compiled when you chose to reference them in that way.  But `{{ assets[myasset.jpg].digest_path }}` is the same as `{% asset myasset.jpg @path %}` if you want to have the asset compiled & reference just data portions.

**Comment by cameronmcefee** [comment]
> But {{ assets[myasset.jpg].digest_path }} is the same as {% asset myasset.jpg @path %} if you want to have the asset compiled & reference just data portions.

Ah nice, that's good to know. My Ruby knowledge is pretty mediocre, since the nomenclature is different between the two methods, I can't just reverse engineer the properties available. Is there a way to inspect the properties available via the `@` syntax, or is @path the only one that I'd ever want to reference that way?

**Comment by cameronmcefee** [comment]
Ah, never mind, I assume that is what is documented here: https://github.com/envygeeks/jekyll-assets#arguments
