### ISSUE TITLE
Optim does not work with jpeg images

### ISSUE THREAD

**Issue by shalzz** [envygeeks/jekyll-assets#546]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [X] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
- [ ] I Am on macOS
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported.

## Description

Using image_optim by adding @optim to asset tag works with PNG but does not seem to work with JPEG images.

Using a preset with `verbose: true` shows a file name passed to image_optim without the file name extension for jpeg images. Which does result in a compressed image being created in _site/assets but with a 6 digit name like "2cc786" resulting in the img tag not being added.
```
✓ 2.473249553s jpeg-recompress --quality high --no-copy /home/shalzz/dev/shalzz.github.io/.jekyll-cache/assets/proxied/a57d43 /tmp/a57d4320180713-25096-zagb6d
✓ 0.587180018s jpegoptim --max\=60 --strip-all --quiet -- /tmp/a57d4320180713-25096-19xb6gy
✓ 1.780206369s jpegrescan -s /tmp/a57d4320180713-25096-19xb6gy /tmp/a57d4320180713-25096-zagb6d
```

Whereas for a PNG image a file name is included and does work fine with a img tag being generated.
```
✓ 2.998024453s pngcrush -reduce -cc -q -rem alla -blacken -- /home/shalzz/dev/shalzz.github.io/.jekyll-cache/assets/proxied/33b84d.png /tmp/33b84d20180713-25096-zt1v66.png
✓ 23.84034526s optipng -strip all -i0 -o 6 -quiet -- /tmp/33b84d20180713-25096-13uqtvp.png
✓ 1.286120012s pngquant --quality\=0-100 --speed\=3 --output\=/tmp/33b84d20180713-25096-zt1v66.png --force 256 -- /tmp/33b84d20180713-25096-13uq
```

NOTE: all images added by me in _assets/images do have a valid extention

**Comment by envygeeks** [comment]
Hey @shalzz,

Can you clarify the issue here, is it that compression is not working (from reading I am going to infer yes,) or that the resulting `<img>` tag is not created, or that the `src` doesn't match the resulting output?

**Comment by shalzz** [comment]
@envygeeks the compression is working but the resulting <img> tag is not created.
