### ISSUE TITLE
Can't locate files while building on TravisCI

### ISSUE THREAD

**Issue by reskir** [envygeeks/jekyll-assets#548]
- [x] I tried updating to the latest version.
- [x] I Am on Linux
  - [x] Ubuntu

## Description

Can't locate files while running my build on `TravisCI`.
Locally everything compiles and works as expected (MacOS).

Travis platform: `x86_64-linux`

<details>
  <summary>_config.yml</summary>
<pre>
assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true # true on JEKYLL_ENV=production
  gzip: true # true on JEKYLL_ENV=production
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: true
  cdn:
    baseurl: true
    destination: false
    url: null
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/js
</pre>
</details>

<details>
  <summary>.travis.yml</summary>
<pre>
language: ruby
rvm:
  - 2.5.0
script: "JEKYLL_ENV=production bundle exec jekyll build"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  verbose: true
  on:
    branch: jekyll-assets
</pre>
</details>

<details>
  <summary>Gemfile</summary>
<pre>
source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
   gem "jekyll-feed"
   gem "jekyll-assets"
   gem 'octopress-autoprefixer'
   gem 'jekyll-seo-tag'
   gem 'jekyll-sitemap'
   gem 'github-pages-health-check'
   gem 'jekyll-paginate'
   gem "image_optim"
   gem "image_optim_pack"
   gem "mini_magick"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
</pre>
</details>

### Versions
```
* jekyll (3.8.3)
* jekyll-assets (3.0.11)
* sprockets (3.7.2)
```

## Output

<details>
  <summary>Output</summary>
<pre>
JEKYLL_ENV=production bundle exec jekyll build
Configuration file: /home/travis/build/repo/project/_config.yml
            Source: /home/travis/build/repo/project
       Destination: /home/travis/build/repo/project/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
[31m  Liquid Exception: couldn't find file ...

Checked in these paths: 
  /home/travis/build/repo/project/assets/css
  /home/travis/build/repo/project/assets/fonts
  /home/travis/build/repo/project/assets/images
  /home/travis/build/repo/project/assets/js
  /home/travis/build/repo/project/assets/videos
  /home/travis/build/repo/project/assets/audios
  /home/travis/build/repo/project/assets/components
  /home/travis/build/repo/project/assets/javascript
  /home/travis/build/repo/project/assets/video
  /home/travis/build/repo/project/assets/audio
  /home/travis/build/repo/project/assets/image
  /home/travis/build/repo/project/assets/img
  /home/travis/build/repo/project/_assets/css
  /home/travis/build/repo/project/_assets/fonts
  /home/travis/build/repo/project/_assets/images
  /home/travis/build/repo/project/_assets/videos
  /home/travis/build/repo/project/_assets/audios
  /home/travis/build/repo/project/_assets/components
  /home/travis/build/repo/project/_assets/javascript
  /home/travis/build/repo/project/_assets/video
  /home/travis/build/repo/project/_assets/audio
  /home/travis/build/repo/project/_assets/image
  /home/travis/build/repo/project/_assets/img
  /home/travis/build/repo/project/_assets/js
  /home/travis/build/repo/project/css
  /home/travis/build/repo/project/fonts
  /home/travis/build/repo/project/images
  /home/travis/build/repo/project/videos
  /home/travis/build/repo/project/audios
  /home/travis/build/repo/project/components
  /home/travis/build/repo/project/javascript
  /home/travis/build/repo/project/audio
  /home/travis/build/repo/project/video
  /home/travis/build/repo/project/image
  /home/travis/build/repo/project/img
  /home/travis/build/repo/project/js
  /home/travis/build/repo/project/.jekyll-cache/assets/proxied
</pre>
</details>

## Expected

Build to run on `Travis`

**Comment by reskir** [comment]
Ignore this issue, seems that I don't push images to repo :/

**Comment by envygeeks** [comment]
We've all had those moments! Glad you got it sorted!

**Comment by reskir** [comment]
@envygeeks Thanks, maybe someone will find this issue helpful, but I wish that nobody will get in such situation :)
