### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by matthewblott** [envygeeks/jekyll-assets#562]
The link to the docs for this repo is broken :-)

https://envygeeks.io/docs/jekyll-assets

**Comment by ByteCommander** [comment]
Any chance to get the documentation available again soon? Or did it move to a different location? 
It's really hard to try and find out about all the possibilities and options with only the repository readme.

**Comment by envygeeks** [comment]
The docs are the same in the readme. The only difference was the design really. I will bring them back up this weekend.

**Comment by araspik** [comment]
It's been a while (*ahem*), and the docs are still down. Any progress? Thanks!

**Comment by envygeeks** [comment]
There are plans for a new docs site soon.
