### ISSUE TITLE
Prevent sprockets from cache busting assets

### ISSUE THREAD

**Issue by amyspark** [envygeeks/jekyll-assets#572]
I'd like to prevent jekyll-assets (and Sprockets) from messing with my assets' names. Is this possible?

This is because, on my *static* web site, I do not need anything other than asset copying and the path management functions. My SASS sheets are processed externally to Jekyll, and it is not possible for me to figure out the exact path of an `url()` asset without messing with the manifest. Also, I employ both `jekyll-seo-tag` and jekyll-assets to access the same hero image, and this results in two copies of the same file.

**Comment by envygeeks** [comment]
This feels like a pretty complicated workflow and an antipattern to what Jekyll Assets was built for.  If you don't want Jekyll Assets to process your assets, why use Jekyll Assets?

**Comment by amyspark** [comment]
I've added Jekyll-Assets to remove myself from handling asset paths. Anyway, I've found the relevant (undocumented) option.

**Comment by envygeeks** [comment]
Glad you found it! Keep it a secret! It's undocumented because it was built and paid for by a client specifically for them.  I don't mind if people use it, I just don't "actively support" it!
