### ISSUE TITLE
Upgrade SASSC ~>2.0 before 4.0 is stable

### ISSUE THREAD

**Issue by sdumetz** [envygeeks/jekyll-assets#577]
If possible (guidelines are unclear about major version upgrade during alpha/beta?), an upgrade would be nice, especially since Sprockets `4.0.0.beta8` has upgraded. It means  this won't be able to keep up with stable updates if it doesn't follows.

I've tested an upgrade locally and it *looks good* (tests OK, *"works on my project*™"). Please let me know if you'd like any follow-up on this subject.

**Comment by envygeeks** [comment]
Add Sprockets 4.0.0.beta8 to your Gemfile, and `jekyll-assets` will use it. The current stable gem was designed to accept anything after Sprockets 3.3, and before 4.1.

**Comment by envygeeks** [comment]
Sprockets 4.x has landed in the master branch and switched to SassC
