### ISSUE TITLE
Assets arent being compiled when deploying to GH-Pages

### ISSUE THREAD

**Issue by afyaf2** [envygeeks/jekyll-assets#583]
Hey all. I have an alpha build of a site im trying to deploy here [https://afyaf2.github.io/ad/](url) but the assets arent compiling at build. I'm not really sure what the error is, I must say I'm a complete noob to jekyll and I'd appreciate any insight. 

Repo is at [https://github.com/afyaf2/ad](url). 

I'd appreciate any help, hoping this is something minor that I've missed. Thanks!

**Comment by davatron5000** [comment]
GitHub pages doesn't support Jekyll plugins. You might want to check out something like [Netlify](https://www.netlify.com/) which can do Jekyll plugins and can autodeploy from a GitHub integration.

**Comment by envygeeks** [comment]
Indeed, Github pages does not support Jekyll-Assets.
