### ISSUE TITLE
Documentation site is down with 404s

### ISSUE THREAD

**Issue by morungos** [envygeeks/jekyll-assets#587]
The documentation URL: https://envygeeks.io/docs/jekyll-assets, linked from the repository, is currently not connecting to anything.

Can we have the documentation back when you have a moment? The readme is okay, but I'm struggling with sass path config and hoping there's more detail somewhere else.

**Comment by envygeeks** [comment]
The documentation in that site is just a clone of the reader it has no more information.

**Comment by morungos** [comment]
Then I will close.
