### ISSUE TITLE
Changes to a JavaScript file included with //= require not reflected when using Jekyll's --incremental rebuild

### ISSUE THREAD

**Issue by Nowaker** [envygeeks/jekyll-assets#596]
- [ ] This feature is not on the latest version

- jekyll 3.8.5
- jekyll-assets: 3.0.12

## Request

`main.js`:
```
//= require common/toggle-pricing
```

`jekyll serve --incremental --livereload`:
```
      Regenerating: 1 file(s) changed at 2019-06-10 14:46:06
                    assets/js/common/toggle-pricing.js
                    ...done in 0.994988 seconds.
```

Request to `http://localhost:4000/assets/js/main-${digest}.js` will not reflect any changes to `toggle-pricing.js` - but should.

**Comment by Nowaker** [comment]
@envygeeks How much would you charge for making jekyll-assets 3.0 `--incremental` friendly? (You can email me if you're interested) The goal would be:

- when `assets/js/common/toggle-pricing.js` is modified, rebuild `assets/main.js` (because it `//= require`s that file)
- when `assets/js/common/toggle-pricing.js` is modified, do not rebuild `assets/blah.js` (because it doesn't `require` that file)
- when Jekyll is run in `--incremental` mode, set `digest: false` automatically (Otherwise a change of digest will require the rebuild of all HTMLs since `{% assets/main.js %}` is on all pages)

**Comment by envygeeks** [comment]
I don't know that I can detect assets with `//= require` but it should be possible I assume. If you'd like to feature this change you can email me.
