### ISSUE TITLE
Allow to disable digest

### ISSUE THREAD

**Issue by Nowaker** [envygeeks/jekyll-assets#599]
Applies to both stable and master jekyll-assets.

## Request

Please consider allowing one to disable digests via a configuration option, e.g. `digest: false`, so assets can be accessed more directly, e.g. `/assets/blah.js` rather than `/assets/blah-$digest.js`.

Rails: https://guides.rubyonrails.org/asset_pipeline.html#turning-digests-off

**Comment by envygeeks** [comment]
Disabling digesting is an unsupported feature as it complicates the logic necessary to maintain this library.  I am willing to give you a hint though: dig through the source, you might have a lucky day, it's unsupported.

**Comment by Nowaker** [comment]
It turns out this is already supported. `assets: false` is all it needs. Implemented in 2017. https://github.com/envygeeks/jekyll-assets/commit/29ddb025f49786794bce67e7d14fe198b04dabe7
