### ISSUE TITLE
Broken alignment of logger output

### ISSUE THREAD

**Issue by ashmaroli** [envygeeks/jekyll-assets#607]
- [x] I tried updating to the latest version
- [x] I Am on Linux
  - [x] Ubuntu

## Description

While debugging a Jekyll site that uses this plugin, I came across the following outputs:
```
           Assets:   Searched for, and rendered non-critical-styles in 0.499893211s
         Rendering: 2001/08/index.html
  Pre-Render Hooks: 2001/08/index.html
  Rendering Markup: 2001/08/index.html
  Rendering Layout: 2001/08/index.html
     Layout source: site
           Assets:   Searched for, and rendered components/archives in 197.469359047s
```

## Expected

Expected aligned topic labels and messages:
```
            Assets: Searched for, and rendered non-critical-styles in 0.499893211s
         Rendering: 2001/08/index.html
  Pre-Render Hooks: 2001/08/index.html
  Rendering Markup: 2001/08/index.html
  Rendering Layout: 2001/08/index.html
     Layout source: site
            Assets: Searched for, and rendered components/archives in 197.469359047s
```

**Comment by envygeeks** [comment]
IMO logs shouldn't be aligned at all like that, it makes it hard to read and makes it hard for machines to parse the output and understand what's going on, typically tabbing and spacing should only be used to indicate sub-context of logs. I have no plans to fix this, sorry.

**Comment by ashmaroli** [comment]
> tabbing and spacing should only be used to indicate sub-context of logs

I think you misunderstood the ticket.
I was requesting the following change:
```diff
-            Assets:   Searched for, and rendered non-critical-styles in 0.499893211s
+             Assets: Searched for, and rendered non-critical-styles in 0.499893211s
           Rendering: 2001/08/index.html
```
However, I haven't checked if the issue was resolved on `master` as of this writing.

**Comment by envygeeks** [comment]
I did not misunderstand anything. What you indicated is what I do not wish to support!

**Comment by ashmaroli** [comment]
Ah! okay then.. :man_shrugging:
