### ISSUE TITLE
compatibility with jekyll-multiple-languages-plugin

### ISSUE THREAD

**Issue by alexandre1985** [envygeeks/jekyll-assets#612]
great plugin. I am having problems with my implementation of cache bust.

I want to use jekyll-assets plugin in conjunction with jekyll-multiple-languages-plugin plugin but this last plugin changes site.baseurl according to which language directory the page is located.

I have 2 solutions, I need your help with this:
1. If there is a way to force a compilation of the asset file when using {{ assets[main.css] }} instead of using the {% asset main.css %} ?
2. Is there a dot variable ( asset[main.css].variable ) available which corresponds to the hash of the asset? (the same way that this variable exist: {{ assets["bundle.css"].content_type }} )?

Any of this would solve my problem.

Also knowing how to use soft cache bust would also solve my problem.

Thank you

**Comment by Nowaker** [comment]
@alexandre1985 I'm using `jekyll-assets` and `jekyll-multiple-languages-plugin` without a problem. What's wrong with `{% asset main.css %}`? This is what I use and it works fine. Did you forget about this?
```
exclude_from_localizations:
- assets
```

**Comment by alexandre1985** [comment]
There were various problems using both plugins.
I already found a way of dealing with this, but I'm gonna try to remember what the problems were.
(Yes, I do have `exclude_from_localizations: ["assets", ....]`)

My goal it to have a (soft) cache bust.
- It would create files in assets/en/
- the soft cache bust was not working (it only did hard cache bust, that is, changed the filename)
- the files in /assets/ were all going to the root of /assets/ directory, not corresponding with the assets sub-directory that they were in.
- I am not remembering everything now, sorry

But I found a way, and I am in the process of ditching `jekyll-assets` plugin (I now only need a jekyll plugin that gives me the hash of the file. I'm thinking of doing that plugin myself, since I am not finding one.... :/ )

**Comment by Nowaker** [comment]
@alexandre1985 Can you share your solution for cache issues?

**Comment by alexandre1985** [comment]
@Nowaker it is not fully working and currently I'm not using cache burst on my websites because of this.
I have made a repository at https://github.com/alexandre1985/jekyll-bustify-plugin

**Comment by Nowaker** [comment]
Thanks @alexandre1985. I use jekyll-assets for more than just cache busting, that's why I was interested.

In the meantime, I came up with a half-solution. It introduces `{% i18n_asset %}` that picks the correct image based on current language. It's not perfect but it works without causing excessive page rebuild times.

```ruby
# {% i18n_asset <all parameters like for asset > %}
#
# On base language site - will serve /assets/blah.png
# On translated sites - will serve /assets/blah.LANG.svg
class LocalizeAsset < Jekyll::Assets::Tag
  def render(ctx)
    config = ctx.registers[:site].config
    current_lang = config['lang']
    languages = config['languages']
    default_lang = config['languages'][0]

    original_args = @args.dup
    correct_ret = nil

    languages.each do |lang|
      if current_lang != default_lang
        all_args = original_args.split ' '
        asset = all_args[0]
        ext = File.extname asset
        i18n_asset = insert_before_last_dot asset, '.' + current_lang
        all_args[0] = i18n_asset
        @args = all_args.join ' '
      end

      # We're processing the asset in each language.
      # It's redundant but is friendly for Jekyll build cache.
      ret = super

      if lang == current_lang
        correct_ret = ret
        if lang != default_lang
          # jekyll-assets links to /assets/file.png because it's not aware it
          # placed the file in /LANG/assets/file.png. We need to fix it.
          correct_ret = config['baseurl'] + ret
        end
      end
    end

    correct_ret
  end
```

**Comment by alexandre1985** [comment]
@Nowaker Thank you. Honestly, I won't use it. As of today, I'm off much of jekyll plugins. I won't use jekyll-assets plugin.  
I believe this may help other developers :smiley:
Have a great day

**Comment by Ivan-Kurochenko** [comment]
@Nowaker can you give me an example repo where you are linking your `.scss` files in an HTML file?
