### ISSUE TITLE
How to include full site url in assets path using font_path

### ISSUE THREAD

**Issue by yukanagai** [envygeeks/jekyll-assets#615]
- [ ] This feature is not on the latest version

## Request

Less of a request than a help question -

How can I use the full site url path within a font.css stylsheet? 

instead of the stylesheet printing `src:url("/assets/#filename") `
I want `src:url("https://website/assets/#filename")`

Here is my font stylehseet:
```
@font-face {
  ....
  src: url(font_path(#filename));
}
```

**Comment by Nowaker** [comment]
@yukanagai I think you need to define `assets:cdn` section in the config. See https://github.com/envygeeks/jekyll-assets#configuration. `JEKYLL_ENV=production` builds will get you an absolute URL instead of a relative one. development builds will still look up locally.

**Comment by envygeeks** [comment]
```yaml
assets:
  full_url: true
```

https://github.com/envygeeks/jekyll-assets/commit/8bc163ccf0b9cc9df7055ab828f7f0adf614f5e3
