### ISSUE TITLE
Include Image Asset Using Liquid Variable

### ISSUE THREAD

**Issue by semireg** [envygeeks/jekyll-assets#62]
Is there any way to pass a variable to an asset command?

```
{% assign badge_url = page_url | append: '/' | append: page_url | append: 'png' %}
{% image badge_url %}
```

Also, is there a way for an asset command to fail gracefully?  For example, if the asset does not exist, it would be nice if it returned null.  Another option would be to include another set of boolean commands such as image_exists, so this could be performed:

```
{% assign badge_url = page_url | append: '/' | append: page_url | append: 'png' %}
{% if image_exists badge_url %}
{% image badge_url %}
{% endif %}
```

**Comment by phillipadsmith** [comment]
@ixti Tried the approaches described above, but I'm hitting this (old and oddly familiar) issue: https://github.com/jekyll-assets/jekyll-assets/issues/121#issuecomment-95358660

Any help appreciated.

Phillip.

**Comment by phillipadsmith** [comment]
Hmmm... actually ```{{ 'file_name' | asset_path }}``` works (no variable, using single quotes around the file name), but ```{{ file_name | asset_path }}``` does not (where file_name is an assigned variable). 

Thoughts on this?

**Comment by chrishough** [comment]
@phillipadsmith sorry, I am not much help on this, will have to defer to others. I moved to Middleman.

**Comment by phillipadsmith** [comment]
@ixti Actually, I figured it out. Never mind. Bad quoting on my part.  :(
