### ISSUE TITLE
Merge javascript selectively 

### ISSUE THREAD

**Issue by gg4u** [envygeeks/jekyll-assets#628]
Hi @envygeeks , I read your comment of this very day, thank you for the effort.

I actually have still to use your plugin, I have a question if eventually you may have already address it.

Suppose I have different Javascript files, some of them but not all of them could be groupd and merged into one file.

Can I use your plugin to instruct how to merge js files?

Example:

```
/assets/js/
/assets/project_one_js/ 
```

I want the files in the second folder grouped in ```proj1.js```, the one in the first as ```main.js```

Is it possible ?

**Comment by envygeeks** [comment]
You cannot. That feature should be taken up with Sprockets as they handle the bulk of asset parsing.
