### ISSUE TITLE
After_compression hook in alternates appears to expect hash, gets string

### ISSUE THREAD

**Issue by elepedus** [envygeeks/jekyll-assets#630]
- [X] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [X] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description
Running production build raises error `Liquid Exception: no implicit conversion of Symbol into Integer in /_layouts/default.html` as per #575. 

Digging around in `alternates.rb`, it appears that lines 65-68 expect the `o` object to be a hash, and attempt to run `gsub` on the `:data` element of that hash. However, in my case, the `o` object is actually a string, and replacing the block with `o.gsub(NODER, " #{NODE3[:raw]} ")` appears to fix the issue.

I am raising this as an issue because I have only recently started using jekyll-assets, and have not taken the time to understand the whole codebase, so I don't know whether this is the right way to address this issue, or what side-effects it might have. 

Could someone with more knowledge of the project sanity-check this finding and let me know if I should submit a PR?

**Comment by envygeeks** [comment]
@elepedus do you have a source repo that can replicate this issue?
