### ISSUE TITLE
Can't figure out how to insert an image

### ISSUE THREAD

**Issue by typhoon2099** [envygeeks/jekyll-assets#655]
I have a file (images/team.jpg) that's defined as the image for a page. The following line
```
{% asset '{{ page.image }}' %}
```

Does not seem to work:
```
Liquid Exception: Couldn't find file '{{ page.image }}' in /srv/jekyll/jekyll/_layouts/home.html
```

I have tried hardcoding the file path (with and without single and double quotes) and get the same error. Am I missing something obvious here? I has assumed I just needed to stick in the path to my image to start resizing etc but so far I have not had a single image rendered correctly.

EDIT: Seems to be the same when creating tags for stylesheets

**Comment by axelson** [comment]
Did you confirm that you're running the latest version of jekyll-assets? Actually you might want to try running with the master branch with `gem 'jekyll-assets', :git => 'https://github.com/envygeeks/jekyll-assets.git', :branch => 'master'` (although I can't remember off the top of my head what I needed from master). I'm using nearly identical code:
```
  {% for project in site.projects %}
  <div class="p-2">
    {% if project.image %}
      <a href="{{ project.link | default: project.url }}" class="block pb-4">
        {% asset '{{project.image}}' %}
      </a>
    {% endif %}
    <a href="{{ project.link | default: project.url }}" class="gotham-medium project-title">
      {{ project.title }}
    </a>
    <div class="py-2 gotham-medium project-subtext">{{ project.subtext }}</div>
    <p>{{ project.excerpt | strip_html }}</p>
  </div>
  {% endfor %}
```

**Comment by typhoon2099** [comment]
I was on the latest version, but not directly from github. IU was under time pressure though so I ended up switching to a different plugin to get image resizing done.
